#!/usr/bin/env bash
# GENERATED by plugin-cursor/scripts/compose.sh — edit plugin/ then re-compose

# --- synaptory: resolve Python interpreter (magic-number safe) ---
# shellcheck source=lib/resolve-python.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib/resolve-python.sh"
: "${SYNAPTORY_PYTHON:?synaptory requires a working Python 3 interpreter (set SYNAPTORY_PYTHON to override)}"
# -------------------------------------------------------------
# Copyright (c) 2024-2026 H3Tech Inc. All rights reserved. PROPRIETARY.
# Production-Grade Session Guard
# Detects if the current project was built with synaptory and offers
# the user a choice: work with the pipeline or without it.

_HOOK_ROOT="${PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
# shellcheck source=lib/resolve-python.sh
source "${_HOOK_ROOT}/hooks/lib/resolve-python.sh"
_py="${SYNAPTORY_PYTHON:-python3}"

SUITE_DIR="${CLAUDE_PROJECT_DIR}/.synaptory"

# Only fire if the suite directory exists in the current project
if [ ! -d "$SUITE_DIR" ]; then
  exit 0
fi

# Count artifacts for context
ADR_COUNT=$(find "$SUITE_DIR" -name "ADR-*.md" 2>/dev/null | wc -l | tr -d ' ')
RECEIPT_COUNT=$(find "$SUITE_DIR/.orchestrator/receipts" -name "*.json" 2>/dev/null | wc -l | tr -d ' ')
PROTOCOL_COUNT=$(find "$SUITE_DIR/.protocols" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')

CONTEXT="# Production-Grade Native Project Detected

This project was built with the synaptory pipeline. The \`.synaptory/\` directory contains ${ADR_COUNT} architecture decisions, ${RECEIPT_COUNT} pipeline receipts, and ${PROTOCOL_COUNT} protocols.

**IMPORTANT — Before starting work, ask the user how they'd like to proceed using AskQuestion:**

Question: \"This project was built with the synaptory pipeline. How would you like to work today?\"
Header: \"Production-Grade Native Project\"
Options:
  1. \"Use synaptory (Recommended)\" — \"Route changes through specialized agents — architecture, security, and test baselines stay intact. Best for features, refactors, and anything that touches system behavior.\"
  2. \"Work directly without the plugin\" — \"Make changes freely. Good for quick fixes, experiments, or when you know exactly what you're changing. You can always invoke /synaptory later if needed.\"
  3. \"Chat about this\" — \"Let's discuss what I'm planning and figure out the best approach together.\"

If the user chooses option 1: invoke /synaptory for their request — it auto-routes to the right mode (Feature, Review, Test, Harden, Ship, Architect, Explore, Optimize).
If the user chooses option 2: proceed normally. Respect the choice fully — no further reminders this session.
If the user chooses option 3: discuss their plans, then recommend an approach.

**Context for the user if they ask why:** This project has ${ADR_COUNT} architecture decisions, ${RECEIPT_COUNT} verified pipeline receipts, and ${PROTOCOL_COUNT} shared protocols. The plugin ensures changes respect these baselines — but it's always your call."

# Output structured JSON for Claude Code to inject as additional context
printf '%s' "$CONTEXT" | SYNAPTORY_HOOK_LIB="${_HOOK_ROOT}/hooks/lib" "$_py" -c "
import sys, os
sys.path.insert(0, os.environ['SYNAPTORY_HOOK_LIB'])
from hook_io import emit
emit('SessionStart', additional_context=sys.stdin.read())
" 2>/dev/null || exit 0
