#!/usr/bin/env python3
# GENERATED by plugin-cursor/scripts/compose.sh — edit plugin/ then re-compose
"""Master validation checklist for synaptory.

Orchestrates all validation scripts in priority order:
  P0: security_scan.py — secrets, injections, insecure patterns
  P1: lint_runner.py — ESLint/Ruff/golangci-lint
  P2: test_runner.py — Jest/pytest/go test with coverage
  P3: accessibility_checker.py + ux_audit.py — WCAG + UX

Flags:
  --stop-on-critical  Halt on P0 failure (used by Autonomous mode)
  --mode <mode>       Engagement mode (autonomous|controlled)
  --json              Output structured JSON

CLI: python3 checklist.py <project_dir> [flags]
"""

import json
import os
import subprocess
import sys
import time
from typing import Any

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))

# Secrets scan command — gitleaks preferred, trufflehog fallback, graceful skip if neither present
_SECRETS_CMD = (
    "gitleaks detect --source . --redact --exit-code 1 --no-banner 2>/dev/null"
    " || trufflehog git file://. --since-commit HEAD~1 --only-verified --fail 2>/dev/null"
    " || echo 'WARN: no secrets scanner found (install gitleaks)'"
)

# Validation stages in priority order
STAGES = [
    {
        "priority": "P0",
        "name": "Secrets Scan",
        "command": _SECRETS_CMD,
        "critical": True,
    },
    {
        "priority": "P0",
        "name": "Security Scan",
        "script": "security_scan.py",
        "critical": True,
    },
    {
        "priority": "P1",
        "name": "Lint",
        "script": "lint_runner.py",
        "critical": False,
    },
    {
        "priority": "P2",
        "name": "Tests",
        "script": "test_runner.py",
        "critical": False,
    },
    {
        "priority": "P3",
        "name": "Accessibility",
        "script": "accessibility_checker.py",
        "critical": False,
    },
]

# Import mode_reader if available
sys.path.insert(0, os.path.join(os.path.dirname(SCRIPTS_DIR), "..", "..", "hooks", "lib"))
try:
    from mode_reader import get_engagement_mode, is_autonomous
except ImportError:
    def get_engagement_mode(project_dir: str) -> str:
        return "autonomous"
    def is_autonomous(project_dir: str) -> bool:
        return True


def run_stage(
    stage: dict[str, Any],
    project_dir: str,
    timeout: int = 120,
) -> dict[str, Any]:
    """Run a single validation stage.

    Stages may specify either a ``script`` (Python file) or a ``command``
    (shell string).  Returns result dict with timing, exit code, output snippet.
    """
    result: dict[str, Any] = {
        "priority": stage["priority"],
        "name": stage["name"],
        "critical": stage["critical"],
    }

    # Determine how to invoke this stage
    if "command" in stage:
        # Shell command — run directly via /bin/sh
        cmd: list[str] | str = stage["command"]
        use_shell = True
        script_path = None
    else:
        script_path = os.path.join(SCRIPTS_DIR, stage["script"])
        cmd = ["python3", script_path, project_dir]
        use_shell = False

    if script_path is not None and not os.path.exists(script_path):
        result["status"] = "skipped"
        result["reason"] = f"Script not found: {stage['script']}"
        result["duration_ms"] = 0
        return result

    start = time.monotonic()
    try:
        proc = subprocess.run(
            cmd,
            cwd=project_dir,
            timeout=timeout,
            capture_output=True,
            text=True,
            shell=use_shell,
        )
        duration_ms = int((time.monotonic() - start) * 1000)
        result["duration_ms"] = duration_ms
        result["exit_code"] = proc.returncode

        # Try to parse JSON output from the script
        try:
            result["output"] = json.loads(proc.stdout)
        except (json.JSONDecodeError, ValueError):
            result["output_text"] = proc.stdout[:2000] if proc.stdout else ""

        if proc.returncode == 0:
            result["status"] = "passed"
            # Surface WARN lines even on success (e.g. "no secrets scanner found")
            if proc.stdout and "WARN:" in proc.stdout:
                result["warning"] = proc.stdout.strip()
        else:
            result["status"] = "failed"
            if proc.stderr:
                result["stderr"] = proc.stderr[:1000]

    except subprocess.TimeoutExpired:
        duration_ms = int((time.monotonic() - start) * 1000)
        result["duration_ms"] = duration_ms
        result["status"] = "timeout"
        result["exit_code"] = -1

    except Exception as e:
        result["duration_ms"] = 0
        result["status"] = "error"
        result["exit_code"] = -1
        result["error"] = str(e)

    return result


def run_checklist(
    project_dir: str,
    stop_on_critical: bool = False,
    mode: str | None = None,
) -> dict[str, Any]:
    """Run the full validation checklist.

    Args:
        project_dir: Project root directory.
        stop_on_critical: Stop on P0 (Critical) failure.
        mode: Engagement mode override.

    Returns:
        Structured result with all stage outcomes.
    """
    if mode is None:
        mode = get_engagement_mode(project_dir)

    autonomous = mode == "autonomous"

    results: list[dict[str, Any]] = []
    total_start = time.monotonic()
    halted = False

    for stage in STAGES:
        stage_result = run_stage(stage, project_dir)
        results.append(stage_result)

        # Stop on critical failure if requested
        if (
            stop_on_critical
            and stage["critical"]
            and stage_result["status"] == "failed"
        ):
            halted = True
            break

    total_duration_ms = int((time.monotonic() - total_start) * 1000)

    passed = sum(1 for r in results if r["status"] == "passed")
    failed = sum(1 for r in results if r["status"] == "failed")
    skipped = sum(1 for r in results if r["status"] == "skipped")

    return {
        "checklist": "synaptory-validation",
        "mode": mode,
        "autonomous": autonomous,
        "halted_on_critical": halted,
        "total_duration_ms": total_duration_ms,
        "summary": {
            "total": len(results),
            "passed": passed,
            "failed": failed,
            "skipped": skipped,
        },
        "stages": results,
    }


def format_compact(result: dict[str, Any]) -> str:
    """Format results compactly for Autonomous mode."""
    lines = ["━━━ Validation Checklist ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"]
    for stage in result["stages"]:
        icon = "✓" if stage["status"] == "passed" else "✗" if stage["status"] == "failed" else "○"
        duration = f"⏱ {stage['duration_ms']}ms" if stage.get("duration_ms") else ""
        lines.append(f"  {icon} {stage['priority']} {stage['name']:<20} {duration}")
        if stage.get("warning"):
            lines.append(f"      ⚠ {stage['warning']}")

    s = result["summary"]
    lines.append(f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append(f"  {s['passed']}/{s['total']} passed    ⏱ {result['total_duration_ms']}ms")
    if result["halted_on_critical"]:
        lines.append("  ⚠ Halted on P0 Critical failure")
    return "\n".join(lines)


def format_detailed(result: dict[str, Any]) -> str:
    """Format results with full detail for Controlled mode."""
    lines = ["━━━ Validation Checklist (Detailed) ━━━━━━━━━━━━━━━━━━━━━━"]
    for stage in result["stages"]:
        icon = "✓" if stage["status"] == "passed" else "✗" if stage["status"] == "failed" else "○"
        lines.append(f"\n  {icon} [{stage['priority']}] {stage['name']} — {stage['status']} ({stage.get('duration_ms', 0)}ms)")
        if "output" in stage and isinstance(stage["output"], dict):
            for k, v in stage["output"].items():
                lines.append(f"      {k}: {v}")
        elif "output_text" in stage and stage["output_text"]:
            for line in stage["output_text"].strip().split("\n")[:10]:
                lines.append(f"      {line}")
        if "stderr" in stage:
            lines.append(f"      stderr: {stage['stderr'][:200]}")

    s = result["summary"]
    lines.append(f"\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append(f"  {s['passed']}/{s['total']} passed, {s['failed']} failed, {s['skipped']} skipped")
    lines.append(f"  Total: {result['total_duration_ms']}ms")
    return "\n".join(lines)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <project_dir> [--stop-on-critical] [--mode <mode>] [--json]", file=sys.stderr)
        sys.exit(1)

    project_dir = sys.argv[1]
    stop_on_critical = "--stop-on-critical" in sys.argv
    json_output = "--json" in sys.argv
    mode = None
    if "--mode" in sys.argv:
        idx = sys.argv.index("--mode")
        if idx + 1 < len(sys.argv):
            mode = sys.argv[idx + 1]

    result = run_checklist(project_dir, stop_on_critical=stop_on_critical, mode=mode)

    if json_output:
        print(json.dumps(result, indent=2))
    elif result.get("autonomous", True):
        print(format_compact(result))
    else:
        print(format_detailed(result))

    # Exit 1 if any failures
    sys.exit(0 if result["summary"]["failed"] == 0 else 1)
