#!/usr/bin/env python3
# GENERATED by plugin-cursor/scripts/compose.sh — edit plugin/ then re-compose
"""
Test Runner — Auto-detects test framework and runs tests with coverage.

Usage:
    python3 test_runner.py [directory]
    python3 test_runner.py --coverage
    python3 test_runner.py --help

Detects: Jest, Vitest, Mocha, pytest, go test, cargo test, RSpec
Stdlib-only — invokes external tools via subprocess.
"""

import argparse
import json
import os
import subprocess
import sys
from typing import Dict, List, Optional


def detect_test_framework(directory: str) -> List[Dict]:
    """Detect which test frameworks are configured."""
    frameworks = []

    pkg_path = os.path.join(directory, "package.json")
    if os.path.exists(pkg_path):
        try:
            with open(pkg_path) as f:
                pkg = json.load(f)
            dev_deps = pkg.get("devDependencies", {})
            deps = pkg.get("dependencies", {})
            all_deps = {**deps, **dev_deps}
            scripts = pkg.get("scripts", {})

            if "vitest" in all_deps:
                frameworks.append({
                    "name": "Vitest",
                    "command": ["npx", "vitest", "run"],
                    "coverage_command": ["npx", "vitest", "run", "--coverage"],
                })
            elif "jest" in all_deps:
                frameworks.append({
                    "name": "Jest",
                    "command": ["npx", "jest", "--watchAll=false"],
                    "coverage_command": ["npx", "jest", "--watchAll=false", "--coverage"],
                })
            elif "mocha" in all_deps:
                frameworks.append({
                    "name": "Mocha",
                    "command": ["npx", "mocha"],
                    "coverage_command": ["npx", "nyc", "mocha"] if "nyc" in all_deps else None,
                })
            elif "test" in scripts:
                # Fall back to npm test
                frameworks.append({
                    "name": "npm test",
                    "command": ["npm", "test", "--", "--watchAll=false"],
                    "coverage_command": None,
                })

            # Playwright / Cypress for e2e
            if "playwright" in all_deps or "@playwright/test" in all_deps:
                frameworks.append({
                    "name": "Playwright",
                    "command": ["npx", "playwright", "test"],
                    "coverage_command": None,
                    "type": "e2e",
                })
            if "cypress" in all_deps:
                frameworks.append({
                    "name": "Cypress",
                    "command": ["npx", "cypress", "run"],
                    "coverage_command": None,
                    "type": "e2e",
                })
        except (json.JSONDecodeError, IOError):
            pass

    # Python
    pyproject_path = os.path.join(directory, "pyproject.toml")
    setup_path = os.path.join(directory, "setup.py")
    requirements_path = os.path.join(directory, "requirements.txt")

    if any(os.path.exists(p) for p in [pyproject_path, setup_path, requirements_path]):
        frameworks.append({
            "name": "pytest",
            "command": ["python", "-m", "pytest", "-v"],
            "coverage_command": ["python", "-m", "pytest", "--cov", "-v"],
        })

    # Go
    if os.path.exists(os.path.join(directory, "go.mod")):
        frameworks.append({
            "name": "go test",
            "command": ["go", "test", "./...", "-v"],
            "coverage_command": ["go", "test", "./...", "-v", "-coverprofile=coverage.out"],
        })

    # Rust
    if os.path.exists(os.path.join(directory, "Cargo.toml")):
        frameworks.append({
            "name": "cargo test",
            "command": ["cargo", "test"],
            "coverage_command": None,
        })

    # Ruby
    if os.path.exists(os.path.join(directory, "Gemfile")):
        frameworks.append({
            "name": "RSpec",
            "command": ["bundle", "exec", "rspec"],
            "coverage_command": None,
        })

    return frameworks


def run_tests(framework: Dict, directory: str, with_coverage: bool = False) -> Dict:
    """Run tests with a specific framework."""
    cmd = framework.get("coverage_command") if (with_coverage and framework.get("coverage_command")) else framework["command"]

    if cmd is None:
        cmd = framework["command"]

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=directory,
            timeout=300,
        )

        # Parse test counts from output (best effort)
        output = result.stdout + result.stderr
        test_info = _parse_test_output(output, framework["name"])

        return {
            "name": framework["name"],
            "type": framework.get("type", "unit"),
            "status": "pass" if result.returncode == 0 else "fail",
            "exit_code": result.returncode,
            "stdout": result.stdout[-3000:] if len(result.stdout) > 3000 else result.stdout,
            "stderr": result.stderr[-1000:] if len(result.stderr) > 1000 else result.stderr,
            "command": " ".join(cmd),
            **test_info,
        }
    except subprocess.TimeoutExpired:
        return {
            "name": framework["name"],
            "status": "timeout",
            "message": "Tests timed out after 300s",
        }
    except FileNotFoundError:
        return {
            "name": framework["name"],
            "status": "not_found",
            "message": f"Command not found: {cmd[0]}",
        }


def _parse_test_output(output: str, framework: str) -> Dict:
    """Try to parse test counts from output."""
    import re

    info = {}

    # Jest/Vitest patterns
    m = re.search(r'Tests:\s+(\d+)\s+passed', output)
    if m:
        info["passed"] = int(m.group(1))
    m = re.search(r'Tests:\s+\d+\s+passed,\s+(\d+)\s+failed', output)
    if m:
        info["failed"] = int(m.group(1))
    m = re.search(r'Test Suites:\s+(\d+)\s+passed', output)
    if m:
        info["suites_passed"] = int(m.group(1))

    # pytest patterns
    m = re.search(r'(\d+)\s+passed', output)
    if m and "passed" not in info:
        info["passed"] = int(m.group(1))
    m = re.search(r'(\d+)\s+failed', output)
    if m and "failed" not in info:
        info["failed"] = int(m.group(1))

    # Go test patterns
    m = re.search(r'ok\s+.*\s+([\d.]+)s', output)
    if m:
        info["duration"] = m.group(1) + "s"

    # Coverage patterns
    m = re.search(r'(?:coverage|Coverage).*?(\d+\.?\d*)%', output)
    if m:
        info["coverage"] = float(m.group(1))

    return info


def main():
    parser = argparse.ArgumentParser(
        description="Test Runner — Auto-detect framework and run tests"
    )
    parser.add_argument("directory", nargs="?", default=".",
                       help="Project directory (default: current directory)")
    parser.add_argument("--coverage", action="store_true",
                       help="Run with coverage enabled")
    parser.add_argument("--type", choices=["unit", "e2e", "all"], default="unit",
                       help="Test type to run (default: unit)")
    parser.add_argument("--format", choices=["text", "json"], default="text",
                       help="Output format")

    args = parser.parse_args()
    directory = os.path.abspath(args.directory)

    if not os.path.isdir(directory):
        print(f"Error: {directory} is not a directory", file=sys.stderr)
        sys.exit(1)

    frameworks = detect_test_framework(directory)
    if not frameworks:
        print("No test frameworks detected", file=sys.stderr)
        sys.exit(1)

    # Filter by type
    if args.type != "all":
        filtered = [f for f in frameworks if f.get("type", "unit") == args.type]
        if not filtered and args.type == "unit":
            filtered = [f for f in frameworks if f.get("type") != "e2e"]
        if filtered:
            frameworks = filtered

    # Run tests
    results = []
    for framework in frameworks:
        result = run_tests(framework, directory, with_coverage=args.coverage)
        results.append(result)

    if args.format == "json":
        print(json.dumps({"results": results}, indent=2))
    else:
        print("━" * 60)
        print("  TEST REPORT")
        print("━" * 60)

        all_pass = True
        for r in results:
            icon = "✓" if r["status"] == "pass" else "✗"
            if r["status"] != "pass":
                all_pass = False

            parts = [f"  {icon} {r['name']}"]
            if "passed" in r:
                parts.append(f"{r['passed']} passed")
            if r.get("failed"):
                parts.append(f"{r['failed']} failed")
            if "coverage" in r:
                parts.append(f"{r['coverage']}% coverage")
            print(", ".join(parts))

            if r["status"] == "fail":
                output = r.get("stdout", "") + r.get("stderr", "")
                if output:
                    lines = output.strip().split('\n')
                    # Show last 15 lines (usually contain the summary/errors)
                    for line in lines[-15:]:
                        print(f"    {line}")

        print("\n" + "━" * 60)
        sys.exit(0 if all_pass else 1)


if __name__ == "__main__":
    main()
