# GENERATED by plugin-cursor/scripts/compose.sh — edit core/ or plugin-claude/ then re-compose
"""Agent backend configuration reader (Claude-only in plugin-claude).

In v2.5, each host plugin uses its own native model family:
- plugin-claude → Claude (this module)
- plugin-cursor → whatever Cursor provides
- plugin-codex / plugin-antigravity → their own native models

Within plugin-claude, every role runs on Claude via the built-in Task()
subagent mechanism. The `agents.default_backend` / `agents.roles` keys in
.synaptory.yaml are no longer used for backend selection — the tier
("opus"/"sonnet"/"haiku") is still resolved per role elsewhere.

This module is kept as a compatibility shim so existing ceremony scripts
that shell out to `backend_config.py <project> <role>` continue to work
(they now always print "claude").

CLI:
    python3 backend_config.py <project_dir> <role_name>
    # prints: claude

    python3 backend_config.py <project_dir>
    # prints all role->"claude" mappings as JSON
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from pathlib import Path


DEFAULT_BACKEND = "claude"
VALID_BACKENDS = frozenset({"claude"})

_CANONICAL_ROLES = [
    "product_owner",
    "software_engineer",
    "quality_engineer",
    "code_reviewer",
    "compliance_engineer",
    "solution_architect",
    "platform_engineer",
    "technical_writer",
    "research_advisor",
]


class BackendConfigError(Exception):
    """Raised when backend configuration is invalid."""


@dataclass
class BackendConfig:
    """Resolved agent backend configuration (always Claude in plugin-claude)."""

    default_backend: str = DEFAULT_BACKEND

    @classmethod
    def load(cls, project_dir: Path) -> BackendConfig:
        """Return a Claude-only config. `project_dir` is accepted for API compat."""
        _ = project_dir  # no-op: retained for API compatibility
        return cls()

    def get_backend(self, role_name: str) -> str:
        _ = role_name
        return DEFAULT_BACKEND

    def all_role_backends(self) -> dict[str, str]:
        return {role: DEFAULT_BACKEND for role in _CANONICAL_ROLES}


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python3 backend_config.py <project_dir> [role_name]",
              file=sys.stderr)
        sys.exit(1)

    config = BackendConfig.load(Path(sys.argv[1]))

    if len(sys.argv) >= 3:
        print(config.get_backend(sys.argv[2]))
    else:
        print(json.dumps(config.all_role_backends(), indent=2))


if __name__ == "__main__":
    main()
