# GENERATED by plugin-cursor/scripts/compose.sh — edit plugin-claude/ then re-compose
"""Pipeline state builders — project, lifecycle, DoD summary, sprint state, context packages."""

import datetime
import json
import os
import re
from pathlib import Path
from typing import Optional

from .helpers import _read, _load_json, _duration_str, _ts_display
from .receipts import extract_findings, SCRUM_STATES, KANBAN_STATES

def build_project(project_dir: Path, settings: dict, config: dict) -> dict:
    project_name = (
        settings.get("project") or
        config.get("project_name") or
        config.get("name") or
        project_dir.name
    )
    return {
        "name": project_name,
        "engagement": settings.get("engagement", "autonomous"),
        "stack": settings.get("stack", config.get("stack", "")),
    }


def build_pipeline(state: dict, receipts: list) -> dict:
    lifecycle_state = state.get("lifecycle_state", "UNKNOWN")
    build_mode = state.get("build_mode", "scrum")

    # Build lifecycle history from v2 state
    lifecycle_history = state.get("lifecycle_history", [])

    # Calculate total elapsed
    started_at = state.get("started_at") or (
        lifecycle_history[0].get("entered_at") if lifecycle_history else None
    )
    total_elapsed = _duration_str(started_at) if started_at else "—"

    # Build history map for lookup
    history_map: dict[str, dict] = {}
    for entry in lifecycle_history:
        s = entry.get("state", "")
        if s not in history_map:
            history_map[s] = entry

    # Select the right state sequence based on build mode
    state_sequence = SCRUM_STATES if build_mode == "scrum" else KANBAN_STATES

    # Build lifecycle stages array
    stages = []
    for stage_name in state_sequence:
        entry = history_map.get(stage_name, {})
        entered_at = entry.get("entered_at")
        exited_at = entry.get("exited_at")

        if stage_name == lifecycle_state:
            status = "active"
            duration = _duration_str(entered_at)
        elif exited_at:
            status = "complete"
            duration = _duration_str(entered_at, exited_at)
        elif entered_at:
            status = "active"
            duration = _duration_str(entered_at)
        else:
            status = "pending"
            duration = "—"

        stages.append({
            "name": stage_name,
            "status": status,
            "entered_at": entered_at or "",
            "exited_at": exited_at or "",
            "duration": duration,
        })

    # Group receipts by story for summary
    stories_by_id: dict[str, list] = {}
    for r in receipts:
        sid = r.get("story_id", "unknown")
        stories_by_id.setdefault(sid, []).append(r)

    return {
        "lifecycle_state": lifecycle_state,
        "build_mode": build_mode,
        "total_elapsed": total_elapsed,
        "stages": stages,
        "stories_with_receipts": len(stories_by_id),
    }


def build_dod_summary(state: dict) -> dict:
    """Build DoD summary from current story states.

    Aggregates per-story DoD evaluation results into an overall summary.
    """
    stories = state.get("current_stories", [])
    total = len(stories)
    evaluated = 0
    passed = 0
    checks_summary: dict[str, dict] = {}

    for story in stories:
        dod = story.get("dod")
        if not dod:
            continue
        evaluated += 1
        if dod.get("passed"):
            passed += 1

        raw_checks = dod.get("checks", {})
        if isinstance(raw_checks, dict):
            checks_iter = []
            for cid, check in raw_checks.items():
                if isinstance(check, dict):
                    checks_iter.append((cid, check))
        elif isinstance(raw_checks, list):
            checks_iter = []
            for check in raw_checks:
                if isinstance(check, dict):
                    checks_iter.append((check.get("id", "unknown"), check))
        else:
            checks_iter = []

        for cid, check in checks_iter:
            if cid not in checks_summary:
                checks_summary[cid] = {"pass": 0, "fail": 0, "skip": 0}

            # v2 state machines write boolean `passed`; older data may use
            # string `result` values such as pass/fail/skip.
            result = check.get("result")
            if result is None:
                if check.get("required") is False and check.get("passed") is None:
                    result = "skip"
                elif check.get("passed") is True:
                    result = "pass"
                elif check.get("passed") is False:
                    result = "fail"
                else:
                    result = "skip"

            if result == "pass":
                checks_summary[cid]["pass"] += 1
            elif result == "skip":
                checks_summary[cid]["skip"] += 1
            else:
                checks_summary[cid]["fail"] += 1

    # Inception gate status
    inception = state.get("inception", {})
    inception_completed = bool(inception.get("completed_at"))

    return {
        "inception_gate": "approved" if inception_completed else "pending",
        "stories_total": total,
        "stories_evaluated": evaluated,
        "stories_passed": passed,
        "pass_rate": round(passed / evaluated, 2) if evaluated else 0.0,
        "checks": checks_summary,
    }


def build_verification(receipts: list) -> dict:
    commands = []
    for r in receipts:
        for cmd in r.get("verification_commands", []):
            if isinstance(cmd, str):
                # v2 simple string format
                commands.append({
                    "story_id": r.get("story_id", ""),
                    "role": r.get("role", ""),
                    "command": cmd,
                    "exit_code": "?",
                    "summary": "",
                })
            elif isinstance(cmd, dict):
                # Legacy dict format
                commands.append({
                    "story_id": r.get("story_id", ""),
                    "role": r.get("role", ""),
                    "command": cmd.get("command", ""),
                    "exit_code": cmd.get("exit_code", "?"),
                    "summary": cmd.get("summary", ""),
                })
    return {"commands": commands}


def build_sprint_state(state: dict, receipts: list) -> Optional[dict]:
    """Extract sprint state from v2 pipeline-state.json.

    Returns None when build_mode is not scrum.
    """
    if state.get("build_mode") != "scrum":
        return None

    current = state.get("current_sprint", 0)
    total = state.get("total_sprints")
    sprint_goal = state.get("sprint_goal", "")
    completed_sprints = state.get("sprints_completed", [])
    current_stories = state.get("current_stories", [])

    # Build per-sprint summary from completed sprint records
    sprint_rows = []
    for sc in completed_sprints:
        sprint_rows.append({
            "number": sc.get("number", 0),
            "stories": f"{sc.get('stories_completed', 0)}/{sc.get('stories_planned', 0)}",
            "velocity": sc.get("velocity", 0),
            "dod_compliance": sc.get("dod_compliance", 0),
            "status": "complete",
        })

    # Add current sprint if active
    if current > 0 and current not in [s.get("number") for s in sprint_rows]:
        stories_by_state: dict[str, int] = {}
        for s in current_stories:
            st = s.get("state", "unknown")
            stories_by_state[st] = stories_by_state.get(st, 0) + 1
        done = stories_by_state.get("done", 0)
        sprint_rows.append({
            "number": current,
            "stories": f"{done}/{len(current_stories)}",
            "velocity": 0,
            "dod_compliance": 0,
            "status": "active",
            "stories_by_state": stories_by_state,
        })

    return {
        "current_sprint": current,
        "total_sprints": total,
        "sprint_goal": sprint_goal,
        "sprints_completed": len(completed_sprints),
        "sprints": sprint_rows,
    }


def build_context_packages(project_dir: Path) -> list:
    pkg_dir = project_dir / ".synaptory" / ".orchestrator" / "context-packages"
    expected = [
        "dependency-map", "interface-contracts", "business-rules-inventory",
        "data-dictionary", "risk-register", "health-assessment",
    ]
    packages = []
    for pkg_name in expected:
        pkg_path = pkg_dir / f"{pkg_name}.md"
        if pkg_path.exists():
            try:
                ts = os.path.getmtime(str(pkg_path))
                dt = datetime.datetime.fromtimestamp(ts, tz=datetime.timezone.utc)
                date = dt.strftime("%Y-%m-%d")
            except Exception:
                date = ""
            packages.append({"name": pkg_name, "status": "generated", "date": date})
        else:
            packages.append({"name": pkg_name, "status": "pending", "date": ""})
    return packages


def build_open_items(receipts: list) -> list:
    """Extract open items from receipts (open_items, open_decisions, blockers)."""
    items = []
    seen = set()
    for r in receipts:
        for field in ("open_items", "open_decisions", "blockers"):
            raw_items = r.get(field, [])
            if isinstance(raw_items, list):
                for item in raw_items:
                    if isinstance(item, str) and item not in seen:
                        seen.add(item)
                        items.append({"description": item, "source_story": r.get("story_id", "")})
                    elif isinstance(item, dict):
                        desc = item.get("description") or item.get("title", "")
                        if desc and desc not in seen:
                            seen.add(desc)
                            items.append({
                                "id": item.get("id", ""),
                                "description": desc,
                                "owner": item.get("owner", ""),
                                "blocks": item.get("blocks", ""),
                                "source_story": r.get("story_id", ""),
                            })
    return items


# ── Data loaders ─────────────────────────────────────────────────────────────

def load_settings(project_dir: Path) -> dict:
    text = _read(project_dir / ".synaptory" / ".orchestrator" / "settings.md")
    result = {}
    for line in text.splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            result[k.strip().lower()] = v.strip()
    return result


def load_config(project_dir: Path) -> dict:
    path = project_dir / ".synaptory.yaml"
    text = _read(path)
    result = {}
    for line in text.splitlines():
        m = re.match(r"^(\w+):\s*(.+)", line.strip())
        if m:
            result[m.group(1)] = m.group(2).strip('"\'')
    return result


def load_receipts_raw(project_dir: Path) -> list:
    receipts_dir = project_dir / ".synaptory" / ".orchestrator" / "receipts"
    receipts = []
    if not receipts_dir.exists():
        return receipts
    for f in sorted(receipts_dir.glob("*.json")):
        data = _load_json(f)
        if data:
            data["_filename"] = f.name
            data["_mtime"] = os.path.getmtime(str(f))
            receipts.append(data)
    return receipts
