# GENERATED by plugin-cursor/scripts/compose.sh — edit plugin-claude/ then re-compose
"""Receipt normalization and findings extraction for v2 story-scoped receipts."""

import os
import re

# v2 role abbreviation mapping for story-scoped receipt naming.
# Canonical direction: abbreviation -> full role name.
ROLE_ABBREV_MAP = {
    "se": "software-engineer", "qe": "quality-engineer", "cr": "code-reviewer",
    "ce": "compliance-engineer", "po": "project-owner", "sa": "solution-architect",
    "pe": "platform-engineer", "tw": "technical-writer", "ra": "research-advisor",
}

# Reverse: full role name -> abbreviation. Legacy alias product-manager → po
# is also accepted at read time for in-flight receipts written by older plugin
# versions.
ROLE_TO_ABBREV = {v: k for k, v in ROLE_ABBREV_MAP.items()}
ROLE_TO_ABBREV["product-manager"] = "po"

# v2 lifecycle states (for reference, not ordering).
SCRUM_STATES = [
    "INCEPTION", "SPRINT_PLANNING", "SPRINT_EXECUTION",
    "SPRINT_REVIEW", "SPRINT_RETRO", "SPRINT_CLOSE",
    "RELEASE", "COMPLETE",
]
KANBAN_STATES = ["DISCOVER", "READY", "EXECUTION", "REVIEW", "RELEASE", "COMPLETE"]


def _extract_story_id_from_filename(filename: str) -> str:
    """Extract story_id from v2 filename like 'US-001-se.json'.

    Strategy: strip .json, then strip the last '-{abbrev}' segment if the
    suffix is a known role abbreviation.
    """
    base = filename.replace(".json", "")
    # Check if the last segment after '-' is a known abbreviation.
    parts = base.rsplit("-", 1)
    if len(parts) == 2 and parts[1] in ROLE_ABBREV_MAP:
        return parts[0]
    return base


def normalize_receipt(raw: dict) -> dict:
    """Normalize v2 story-scoped receipt into canonical form."""
    # Story ID: explicit field > extracted from filename
    story_id = (
        raw.get("story_id")
        or _extract_story_id_from_filename(raw.get("_filename", ""))
        or "unknown"
    )

    # Agent/role: accept role or agent
    role = raw.get("role") or raw.get("agent") or "unknown"

    # Backend + model traceability
    backend = raw.get("backend", "unknown")
    model = raw.get("model", "unknown")

    # Metrics
    metrics = raw.get("metrics", {})

    # Artifacts
    artifacts = raw.get("artifacts") or raw.get("outputs") or []
    if isinstance(artifacts, list):
        key_artifacts = [os.path.basename(str(a)) for a in artifacts[:5] if a]
        artifacts_count = len(artifacts)
    else:
        key_artifacts = []
        artifacts_count = 0

    # Verification commands
    verification_commands = raw.get("verification_commands", [])

    # Story DoD (per-story Definition of Done evaluation)
    story_dod = raw.get("story_dod", {})

    # Confidence
    confidence = raw.get("confidence", {})

    # Completed timestamp
    completed_at = raw.get("completed_at", "")

    return {
        "story_id": story_id,
        "role": role,
        "backend": backend,
        "model": model,
        "metrics": metrics,
        "artifacts_count": artifacts_count,
        "key_artifacts": key_artifacts,
        "verification_commands": verification_commands,
        "story_dod": story_dod,
        "confidence": confidence,
        "completed_at": completed_at,
        # Preserve original filename for receipt matching
        "_filename": raw.get("_filename", ""),
        # Preserve structured findings/fixes for extraction
        "_findings": raw.get("findings", {}),
        "_fixes": raw.get("fixes", []),
        "_blocking_issues": raw.get("blocking_issues", []),
        "_sr_results": raw.get("sr_results", {}),
    }


def extract_findings(receipts: list) -> dict:
    """Build structured findings from receipt data only (no markdown regex).

    Collects findings from all agent receipts (QE, CE, CR, and others).
    """
    items = []
    summary = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    fixed = {"critical": 0, "high": 0, "medium": 0, "low": 0}

    for r in receipts:
        findings_data = r.get("_findings", {})
        role = r["role"]
        story_id = r["story_id"]

        # Case 1: findings is a list of structured items
        if isinstance(findings_data, list):
            for f in findings_data:
                sev = f.get("severity", "medium").lower()
                items.append({
                    "id": f.get("id", ""),
                    "title": f.get("title", ""),
                    "severity": sev,
                    "status": f.get("status", "open"),
                    "fixed_by": f.get("fixed_by", ""),
                    "source_role": role,
                    "source_story": story_id,
                    "file_ref": f.get("file_ref", ""),
                    "description": f.get("description", ""),
                })
                summary[sev] = summary.get(sev, 0) + 1

        # Case 2: findings is a summary dict with counts
        elif isinstance(findings_data, dict) and any(
            k in findings_data for k in ("critical", "high", "medium", "low", "total")
        ):
            for sev in ("critical", "high", "medium", "low"):
                raw = findings_data.get(sev, 0)
                # A receipt may express per-severity findings as a list of
                # objects (e.g. {"high": [{...}, {...}]}) rather than a scalar
                # count. Coerce to an int so aggregation never raises (#145).
                count = len(raw) if isinstance(raw, list) else (raw if isinstance(raw, int) else 0)
                summary[sev] = summary.get(sev, 0) + count

            # Extract blocking_issues as individual finding items
            for issue in r.get("_blocking_issues", []):
                if isinstance(issue, str):
                    # Parse "SR-01: Description" format
                    m = re.match(r"^([\w-]+):\s*(.+)", issue)
                    fid = m.group(1) if m else ""
                    title = m.group(2) if m else issue
                    items.append({
                        "id": fid,
                        "title": title,
                        "severity": "critical",
                        "status": "open",
                        "fixed_by": "",
                        "source_role": role,
                        "source_story": story_id,
                        "file_ref": "",
                        "description": "",
                    })

            # Extract SR results as findings
            for sr_id, result in r.get("_sr_results", {}).items():
                if result in ("FAIL", "PARTIAL", "NOT_IMPLEMENTED"):
                    sev = "critical" if result == "FAIL" else "medium"
                    items.append({
                        "id": sr_id,
                        "title": f"{sr_id}: {result}",
                        "severity": sev,
                        "status": "open",
                        "fixed_by": "",
                        "source_role": role,
                        "source_story": story_id,
                        "file_ref": "",
                        "description": "",
                    })

    # Apply fixes from remediation receipts
    fixes_applied = []
    for r in receipts:
        fixes = r.get("_fixes", [])
        story_id = r["story_id"]
        for fix in fixes:
            if isinstance(fix, dict):
                finding_ref = fix.get("finding") or fix.get("finding_id") or fix.get("id", "")
                sev = fix.get("severity", "").lower()
                fixes_applied.append({
                    "finding_ref": finding_ref,
                    "severity": sev,
                    "fixed_by": story_id,
                    "title": fix.get("title", ""),
                    "description": fix.get("description", ""),
                })

    # Mark items as fixed based on fixes
    for fix in fixes_applied:
        matched = False
        for item in items:
            if (fix["finding_ref"] and
                (fix["finding_ref"] in item["id"] or
                 item["id"] in fix["finding_ref"])):
                item["status"] = "fixed"
                item["fixed_by"] = fix["fixed_by"]
                matched = True
                break
        # If no existing item matched, add the fix as a resolved finding
        if not matched and fix.get("title"):
            sev = fix["severity"] if fix["severity"] in summary else "high"
            items.append({
                "id": fix["finding_ref"],
                "title": fix["title"],
                "severity": sev,
                "status": "fixed",
                "fixed_by": fix["fixed_by"],
                "source_role": "remediation",
                "source_story": fix["fixed_by"],
                "file_ref": "",
                "description": fix.get("description", ""),
            })

    # Count fixed items
    for item in items:
        if item["status"] == "fixed":
            sev = item["severity"]
            fixed[sev] = fixed.get(sev, 0) + 1

    # If we have fixes but no items from verification, infer fixed counts from fix severities
    if fixes_applied and not any(i["status"] == "open" for i in items):
        for fix in fixes_applied:
            sev = fix["severity"]
            if sev in fixed:
                fixed[sev] = fixed.get(sev, 0) + 1

    # Deduplicate items by id
    seen_ids = set()
    unique_items = []
    for item in items:
        key = item["id"] or item["title"][:60]
        if key not in seen_ids:
            seen_ids.add(key)
            unique_items.append(item)

    # Sort by severity
    SEV_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    unique_items.sort(key=lambda x: SEV_ORDER.get(x["severity"], 4))

    return {
        "summary": summary,
        "fixed": fixed,
        "items": unique_items,
    }
