# GENERATED by plugin-cursor/scripts/compose.sh — edit plugin/ then re-compose
"""Phase 5 — append one OTLP span event to the per-session JSONL log.

The hook scripts ``synaptory-inject-protocols.sh`` (SubagentStart) and
``synaptory-verify-receipt.sh`` (SubagentStop) shell out here once each.
Span events accumulate in
``.synaptory/.orchestrator/otel/spans-<session_id>.jsonl``;
the Stop hook (or the next session's bootstrap) calls
``synaptory telemetry traces --file <jsonl>`` which translates the
batch into the OTLP ``resourceSpans`` shape and posts to /v1/traces.

JSONL line shape (CLI-internal, not OTLP):

    {"event":"start","span_id":"…","trace_id":"…","role":"…",
     "backend":"…","model":"…","story_id":"…","start_ns":1736e15}
    {"event":"end","span_id":"…","end_ns":1736e15,
     "status":"ok"}                      # or
    {"event":"end","span_id":"…","end_ns":1736e15,
     "status":"error","message":"timeout"}

Kept separate from the bash hooks so it can be unit-tested and so the
file-lock behaviour is consistent across the two call sites.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time
import uuid
from pathlib import Path
from typing import Any

# Deterministic span_id derivation from Claude Code's agent_id so
# SubagentStart and SubagentStop produce the same id without having
# to plumb state between two separate hook invocations. Same
# namespace pattern as the CLI's resolveSubagentID (telemetry.go).
_AGENT_ID_NS = uuid.UUID("8a6cdf0d-2adb-4d20-9c0a-9dc81b5b6c34")


def derive_span_id(agent_id: str) -> str:
    """Map an opaque Claude Code agent_id to a stable 32-hex span id.

    OTLP requires 16-byte span ids (32 hex chars). UUIDv5(agent_id) is
    16 bytes; .hex strips dashes. Same agent_id → same span id, so
    start and end events correlate without a side index file."""
    if not agent_id:
        return uuid.uuid4().hex
    return uuid.uuid5(_AGENT_ID_NS, agent_id).hex


def derive_trace_id(session_id: str) -> str:
    """Map a session id to a stable trace id. All spans inside the same
    Claude Code session share a trace, which is what /reliability
    wants for grouping. 16-byte trace id (32 hex chars)."""
    if not session_id:
        return uuid.uuid4().hex
    # Salt with a fixed string so trace_id ≠ session_id (which is
    # already a UUID and shouldn't be reused as a trace id directly).
    h = hashlib.sha256(f"synaptory-trace|{session_id}".encode()).hexdigest()
    return h[:32]


def _now_ns() -> int:
    return time.time_ns()


def _ensure_dir(p: Path) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)


def _atomic_append(path: Path, line: str) -> None:
    """O_APPEND is atomic on POSIX for writes < PIPE_BUF (4096 on Linux).
    Our lines are ~150 bytes; we don't need flock."""
    _ensure_dir(path)
    with open(path, "a", encoding="utf-8") as f:
        f.write(line.rstrip("\n") + "\n")


def jsonl_path(suite_dir: Path, session_id: str) -> Path:
    """Resolve the per-session span file. ``session_id`` may be empty for
    pre-session events; we shunt those into ``spans-no-session.jsonl`` so
    they still ship."""
    sid = session_id or "no-session"
    return suite_dir / ".orchestrator" / "otel" / f"spans-{sid}.jsonl"


def append_event(suite_dir: Path, session_id: str, event: dict[str, Any]) -> Path:
    """Append a single JSON event to the per-session JSONL file."""
    path = jsonl_path(suite_dir, session_id)
    _atomic_append(path, json.dumps(event, separators=(",", ":")))
    return path


def build_start(
    *,
    span_id: str | None,
    trace_id: str | None,
    role: str,
    backend: str | None,
    model: str | None,
    story_id: str | None,
    prompt_id: str | None = None,
    start_ns: int | None = None,
) -> dict[str, Any]:
    """Construct the {event:start} record. span_id and trace_id are
    auto-generated when absent — the SubagentStart hook always wants a
    fresh one. We use UUIDv4 hex; the CLI converts to OTLP's expected
    hex format on flush.

    prompt_id is the per-turn UUID available in Claude Code v2.1.196+
    hook stdin envelopes. When present it improves reliability/latency
    granularity from per-session to per-turn in the OTel backend."""
    rec: dict[str, Any] = {
        "event": "start",
        "span_id": (span_id or uuid.uuid4().hex)[:32],
        "trace_id": (trace_id or uuid.uuid4().hex)[:32],
        "role": role or "unknown",
        "backend": backend or "",
        "model": model or "",
        "story_id": story_id or "",
        "start_ns": start_ns if start_ns is not None else _now_ns(),
    }
    if prompt_id:
        rec["prompt_id"] = prompt_id[:64]
    return rec


def build_end(
    *,
    span_id: str,
    end_ns: int | None = None,
    status: str = "ok",
    message: str | None = None,
) -> dict[str, Any]:
    """Construct the {event:end} record. ``status`` is "ok" or "error"
    — the CLI maps these to OTLP status codes 1 and 2 on flush."""
    out: dict[str, Any] = {
        "event": "end",
        "span_id": span_id,
        "end_ns": end_ns if end_ns is not None else _now_ns(),
        "status": status,
    }
    if message:
        out["message"] = message
    return out


def main() -> int:
    """CLI surface, used by the shell hooks.

    Usage:
        otel_writer.py start --suite-dir … --session-id … --role …
            [--backend …] [--model …] [--story-id …] [--span-id …]
            [--trace-id …]

        otel_writer.py end --suite-dir … --session-id … --span-id …
            [--status ok|error] [--message …]

    Writes the appended event to stdout as JSON so the caller can read
    back the assigned span_id (useful for the start variant; the end
    variant just echoes the input).
    """
    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest="event", required=True)

    s = sub.add_parser("start")
    s.add_argument("--suite-dir", required=True)
    s.add_argument("--session-id", default="")
    # Either pass agent-id (derives span_id deterministically) or span-id
    # directly; agent-id is what the SubagentStart hook has on hand.
    s.add_argument("--agent-id", default="")
    s.add_argument("--span-id", default="")
    s.add_argument("--trace-id", default="")
    s.add_argument("--role", default="")
    s.add_argument("--backend", default="")
    s.add_argument("--model", default="")
    s.add_argument("--story-id", default="")
    s.add_argument("--prompt-id", default="")

    e = sub.add_parser("end")
    e.add_argument("--suite-dir", required=True)
    e.add_argument("--session-id", default="")
    e.add_argument("--agent-id", default="")
    e.add_argument("--span-id", default="")
    e.add_argument("--status", default="ok", choices=("ok", "error"))
    e.add_argument("--message", default="")

    args = p.parse_args()

    suite = Path(args.suite_dir)
    span_id = args.span_id or (derive_span_id(args.agent_id) if args.agent_id else "")
    if args.event == "start":
        trace_id = args.trace_id or (
            derive_trace_id(args.session_id) if args.session_id else ""
        )
        evt = build_start(
            span_id=span_id or None,
            trace_id=trace_id or None,
            role=args.role,
            backend=args.backend,
            model=args.model,
            story_id=args.story_id,
            prompt_id=args.prompt_id or None,
        )
    else:
        if not span_id:
            print("otel_writer: end requires --span-id or --agent-id", file=sys.stderr)
            return 0
        evt = build_end(
            span_id=span_id,
            status=args.status,
            message=args.message or None,
        )

    append_event(suite, args.session_id, evt)
    print(json.dumps(evt))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:
        # Telemetry must never break a hook. Print the error to stderr
        # and exit 0 so the caller continues.
        print(f"otel_writer: {exc}", file=sys.stderr)
        sys.exit(0)


__all__ = [
    "append_event",
    "build_end",
    "build_start",
    "jsonl_path",
]
