#!/usr/bin/env bash
# GENERATED by plugin-cursor/scripts/compose.sh — edit core/ or plugin-claude/ then re-compose
# Copyright (c) 2024-2026 H3Tech Inc. All rights reserved. PROPRIETARY.
#
# Hook: PostToolUse (every tool call) + Stop (session wind-down).
# Purpose: Ship a one-line "what just happened" activity ping to the
# control-plane outbox. The CLI batches and POSTs to /v1/activity in
# the background; the hot path is one CLI invocation that appends to
# a local file and exits.
#
# Hot-path budget: < 50 ms p95. We do as little work as possible —
#   1. Parse stdin JSON for {tool_name, tool_input} via a tiny Python
#      one-liner (already-resident interpreter; ~10 ms cold start).
#   2. Build a one-line summary keyed off tool_name.
#   3. Call `synaptory telemetry activity` once (the CLI writes one
#      outbox row).
# Since #446 the hook also records catalog retrievals locally. That costs a
# python spawn only on a tool call whose payload mentions `skills get`,
# `agents/` or `.protocols/`, plus one more on the first tool call of a run
# directory; every other tool call pays a bash `case` and an `[ -f ]` test.
# Silent on failure: never block a tool call because telemetry can't
# ship. The user does real work; telemetry is best-effort.

set -u  # do NOT set -e — we deliberately tolerate every failure path.

_HOOK_ROOT="${PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
# shellcheck source=lib/resolve-python.sh
source "${_HOOK_ROOT}/hooks/lib/resolve-python.sh" 2>/dev/null || exit 0
_py="${SYNAPTORY_PYTHON:-python3}"

# Only fire inside a synaptory project. Outside `.synaptory/` the user
# is running Claude Code ad-hoc and we shouldn't generate telemetry.
SUITE_DIR="${CLAUDE_PROJECT_DIR:-}/.synaptory"
if [ -z "${CLAUDE_PROJECT_DIR:-}" ] || [ ! -d "$SUITE_DIR" ]; then
  exit 0
fi

# Read stdin once. PostToolUse stdin shape (per Claude Code):
#   {"tool_name":"Edit","tool_input":{...},"tool_output":"...",
#    "session_id":"...","cwd":"...","hook_event_name":"PostToolUse"}
# Stop stdin is a thinner envelope without tool_input.
#
# Read BEFORE the CLI gate below. The local skill_fetch signal (#446) is a
# file append into this run's own directory and needs no CLI at all, so it
# must not be skipped just because the control-plane ping cannot ship.
INPUT="$(cat 2>/dev/null || true)"

# --- #446: local JIT-retrieval signal -------------------------------------
# #404 and #480 made tech packs, phase guides and five agent bodies fetchable
# instead of mandatory. That converts a measured cost into an unmeasured one
# unless the retrieval is recorded, and nothing recorded it: the ping below
# ships `Bash: <first line>` / `Read: <path>` summaries to the control-plane
# outbox with no dispatching role and no story, so `pilot_metrics` reported
# ABSENT for measured JIT volume. This writes the missing producer half into
# `.synaptory/.orchestrator/skill-fetches.jsonl`, beside the run data every
# other pilot metric reads.
#
# Local-first and CLI-free by construction: one append to one file. An
# unstamped tree resolves no CLI (#320, #425) and this block never asks for
# one, so it behaves the same there.
#
# Two python spawns are gated so the common tool call pays for neither:
#   * `arm` runs at most once per run directory, when the log does not exist
#     yet. It is what keeps ABSENT and zero apart — a run whose producer was
#     installed and fetched nothing reports a measured 0, while a run on a
#     tree without this block leaves no file and reports ABSENT.
#   * `record` runs only when the raw payload mentions one of the three
#     substrings a real retrieval must contain. The prefilter is a bash
#     `case` over the untruncated stdin, NOT over the activity summary built
#     below: that summary is clipped to 120 chars, so filtering on it would
#     miss a retrieval sitting inside a long compound command. False
#     positives cost one python spawn and are re-checked properly there.
SKILL_FETCH_LOG="${_HOOK_ROOT}/hooks/lib/skill_fetch_log.py"
if [ -f "$SKILL_FETCH_LOG" ]; then
  _sf_log="${SUITE_DIR}/.orchestrator/skill-fetches.jsonl"
  if [ ! -f "$_sf_log" ]; then
    "$_py" "$SKILL_FETCH_LOG" arm "$CLAUDE_PROJECT_DIR" >/dev/null 2>&1 || true
  fi
  case "$INPUT" in
    *"skills get"*|*"agents/"*|*".protocols/"*)
      printf '%s' "$INPUT" \
        | "$_py" "$SKILL_FETCH_LOG" record "$CLAUDE_PROJECT_DIR" \
          >/dev/null 2>&1 || true
      ;;
  esac
fi

# Resolve the CLI; silently bail if unavailable so a missing CLI
# doesn't break Claude Code itself.
cli=$("${_HOOK_ROOT}/hooks/_resolve-cli.sh" 2>/dev/null || true)
if [[ -z "$cli" ]] || [[ ! -x "$cli" ]]; then
  exit 0
fi

# Extract tool + summary. The summary line is intentionally minimal —
# we ship file paths and the head of bash commands, not full args.
# Python parser script (kept in lib/ so the hook stays inspectable).
ACTIVITY_PARSER="${_HOOK_ROOT}/hooks/lib/activity_parser.py"
if [ ! -f "$ACTIVITY_PARSER" ]; then
  exit 0
fi
PARSED=$(printf '%s' "$INPUT" | "$_py" "$ACTIVITY_PARSER" 2>/dev/null || true)
TOOL_NAME=$(printf '%s' "$PARSED" | sed -n '1p')
SUMMARY=$(printf '%s' "$PARSED" | sed -n '2p')
# Claude Code's session_id (third parser line). Forwarded to the CLI so the
# event is attributed to the session's bound project, not the process cwd — a
# `cd` into another repo must not re-home the ping (issue #117).
SESSION_ID=$(printf '%s' "$PARSED" | sed -n '3p')

# Empty tool name → couldn't parse stdin (Stop event with no tool_name,
# or stdin malformed). For Stop we still want to record a turn boundary
# so the feed shows "session activity" even when no tools were called.
HOOK_EVENT="${SYNAPTORY_HOOK_EVENT:-PostToolUse}"
if [ -z "$TOOL_NAME" ] && [ "$HOOK_EVENT" = "Stop" ]; then
  TOOL_NAME="Stop"
  SUMMARY="Turn ended"
fi

# No tool, no summary — nothing useful to ship.
if [ -z "$TOOL_NAME" ] && [ -z "$SUMMARY" ]; then
  exit 0
fi

# Fire the CLI in the background with a clipped argv. The CLI itself
# is hot-path safe (writes one outbox row), but starting a subprocess
# is still ~10-20 ms — sending it to the background lets PostToolUse
# return immediately.
(
  "$cli" telemetry activity \
    --kind tool_call \
    --tool "$TOOL_NAME" \
    --summary "$SUMMARY" \
    ${SESSION_ID:+--session-id "$SESSION_ID"} \
    >/dev/null 2>&1
) &
disown 2>/dev/null || true

exit 0
