#!/usr/bin/env bash
# GENERATED by plugin-cursor/scripts/compose.sh — edit plugin-claude/ then re-compose
# Copyright (c) 2024-2026 H3Tech Inc. All rights reserved. PROPRIETARY.
#
# Hook: Stop  (blocking — the FIRST Stop hook; sync, <500ms budget)
# Purpose: Loop Engineering P2 (epic #75). When Claude stops mid-execution
# with dispatchable work remaining and no human gate pending, emit
# {"decision":"block","reason": …} so the session keeps driving the story
# pipeline instead of relying on the model to remember to continue.
#
# All decision logic is in hooks/lib/loop_engine.py (unit-tested). This hook
# is a thin adapter that resolves the project dir + active spec, runs the
# engine, prints the Stop JSON, and ships best-effort loop telemetry.
#
# HARD RULE: this hook must NEVER exit non-zero and must fail toward LETTING
# THE SESSION STOP. A broken loop hook that blocked stopping would trap the
# user. Any error path → exit 0 with no output (session stops normally).

set -u

_HOOK_ROOT="${PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
# shellcheck source=lib/resolve-python.sh
source "${_HOOK_ROOT}/hooks/lib/resolve-python.sh" 2>/dev/null || exit 0
_py="${SYNAPTORY_PYTHON:-python3}"

# Only inside a synaptory project.
if [ -z "${CLAUDE_PROJECT_DIR:-}" ] || [ ! -d "${CLAUDE_PROJECT_DIR}/.synaptory" ]; then
  exit 0
fi

INPUT="$(cat 2>/dev/null || true)"

# session_id drives the runaway guard's per-session reset. Pull it from the
# Stop stdin envelope; empty is fine (guard just treats it as one session).
SESSION_ID=$(printf '%s' "$INPUT" | "$_py" -c "
import sys, json
try:
    print(json.load(sys.stdin).get('session_id') or '')
except Exception:
    print('')
" 2>/dev/null || printf '')

# Resolve the active spec exactly as synaptory-verify-receipt.sh does, so the
# engine reads the same spec's board (multi-spec projects, docs/multi-spec).
if [ -z "${SYNAPTORY_ACTIVE_SPEC:-}" ] \
   && [ -r "${CLAUDE_PROJECT_DIR}/.synaptory/.orchestrator/pipeline-state.json" ]; then
  SYNAPTORY_ACTIVE_SPEC=$(
    sed -n 's/.*"active_spec"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
      "${CLAUDE_PROJECT_DIR}/.synaptory/.orchestrator/pipeline-state.json" | head -n1
  )
  [ -n "$SYNAPTORY_ACTIVE_SPEC" ] && export SYNAPTORY_ACTIVE_SPEC
fi

ENGINE="${_HOOK_ROOT}/hooks/lib/loop_engine.py"
[ -f "$ENGINE" ] || exit 0

# Run the engine. Any failure → no output → session stops (fail-safe).
DECISION=$("$_py" "$ENGINE" "${CLAUDE_PROJECT_DIR}" "${SESSION_ID}" 2>/dev/null || printf '')
[ -n "$DECISION" ] || exit 0

# Parse the decision: print the Stop JSON when continuing; capture any
# telemetry activity to ship in the background.
OUT=$(printf '%s' "$DECISION" | "$_py" -c "
import sys, json
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
# Line 1: the Stop-hook JSON to print (empty = allow stop).
if d.get('continue') and d.get('reason'):
    print(json.dumps({'decision': 'block', 'reason': d['reason']}))
else:
    print('')
# Line 2/3: telemetry activity kind + summary (empty = none).
act = d.get('activity') or {}
print(act.get('kind') or '')
print(act.get('summary') or '')
" 2>/dev/null || printf '\n\n')

STOP_JSON=$(printf '%s' "$OUT" | sed -n '1p')
ACT_KIND=$(printf '%s' "$OUT" | sed -n '2p')
ACT_SUMMARY=$(printf '%s' "$OUT" | sed -n '3p')

# Ship loop telemetry best-effort in the background (never blocks the hook,
# never affects the decision). loop_continue / loop_guard_trip feed
# /reliability and the events monitor.
if [ -n "$ACT_KIND" ]; then
  cli=$("${_HOOK_ROOT}/hooks/_resolve-cli.sh" 2>/dev/null || true)
  if [ -n "$cli" ] && [ -x "$cli" ]; then
    (
      "$cli" telemetry activity --kind "$ACT_KIND" --tool "loop-continue" \
        --summary "$ACT_SUMMARY" >/dev/null 2>&1
    ) &
    disown 2>/dev/null || true
  fi
fi

# Emit the Stop JSON (blocks the stop) or nothing (allows it).
if [ -n "$STOP_JSON" ]; then
  printf '%s\n' "$STOP_JSON"
fi
exit 0
