# GENERATED by plugin-cursor/scripts/compose.sh — edit plugin/ then re-compose
"""Report output functions — sprint reports and versioned reports."""

import json
from pathlib import Path

from .helpers import check_immutability, write_report_meta
from .versioned import (
    render_requirements_html,
    render_technical_html,
    render_quality_html,
    render_progress_html,
    render_changelog_html,
)

def write_sprint_reports(
    project_dir: Path,
    sprint_num: int,
    sprint_type: str = "dev",
    overwrite: bool = False,
) -> list[Path]:
    """Generate and write quality + progress HTML for a sprint."""
    reports_dir = project_dir / ".synaptory" / "reports"

    # Determine folder name
    if sprint_type == "hardening":
        folder = "hardening"
    elif sprint_type == "uat":
        folder = "uat"
    else:
        folder = f"sprint-{sprint_num}"

    # Check immutability
    if _check_immutability(reports_dir, folder) and not overwrite:
        raise RuntimeError(
            f"Sprint reports in '{folder}' are locked. Use --overwrite to regenerate."
        )

    target_dir = reports_dir / folder
    target_dir.mkdir(parents=True, exist_ok=True)

    # Load sprint data
    data_path = target_dir / "sprint-data.json"
    if not data_path.exists():
        raise FileNotFoundError(
            f"Sprint data not found at {data_path}. Run build_summary.py first."
        )
    data = json.loads(data_path.read_text(encoding="utf-8"))
    data["sprint_type"] = sprint_type
    data["locked"] = not overwrite

    outputs: list[Path] = []

    # Render quality.html
    quality_path = target_dir / "quality.html"
    quality_path.write_text(render_quality_html(data), encoding="utf-8")
    outputs.append(quality_path)

    # Render progress.html
    progress_path = target_dir / "progress.html"
    progress_path.write_text(render_progress_html(data), encoding="utf-8")
    outputs.append(progress_path)

    # Write report meta
    stories = data.get("stories", {})
    _write_report_meta(
        target_dir,
        sprint_num,
        stories.get("planned", 0),
        stories.get("completed", 0),
    )

    return outputs


def write_versioned_report(
    project_dir: Path, report_type: str
) -> list[Path]:
    """Generate and write versioned requirements or technical report."""
    reports_dir = project_dir / ".synaptory" / "reports"
    type_dir = reports_dir / report_type
    type_dir.mkdir(parents=True, exist_ok=True)

    # Find latest version
    latest = _get_latest_version(reports_dir, report_type)
    version = latest + 1

    # Load data
    data_path = type_dir / f"v{version}.data.json"
    if not data_path.exists():
        # Fall back to latest.data.json
        data_path = type_dir / "latest.data.json"
    if not data_path.exists():
        raise FileNotFoundError(
            f"Report data not found at {type_dir}/v{version}.data.json or latest.data.json. "
            f"Run build_summary.py first."
        )
    data = json.loads(data_path.read_text(encoding="utf-8"))
    data["version"] = version
    data["locked"] = True

    outputs: list[Path] = []

    # Render main report
    if report_type == "requirements":
        html_content = render_requirements_html(data)
    elif report_type == "technical":
        html_content = render_technical_html(data)
    else:
        raise ValueError(f"Unknown report type: {report_type}")

    versioned_path = type_dir / f"v{version}.html"
    versioned_path.write_text(html_content, encoding="utf-8")
    outputs.append(versioned_path)

    # Render changelog
    changelog_items = data.get("changelog", {}).get("items", [])
    if changelog_items:
        cl_path = type_dir / f"v{version}-changelog.html"
        cl_path.write_text(
            render_changelog_html(data, report_type, version), encoding="utf-8"
        )
        outputs.append(cl_path)

    # Copy to latest.html
    latest_path = type_dir / "latest.html"
    latest_path.write_text(html_content, encoding="utf-8")
    outputs.append(latest_path)

    return outputs

