#!/usr/bin/env python3
# GENERATED by plugin-cursor/scripts/compose.sh — edit plugin-claude/ then re-compose
"""
validate_skill_docs.py — Validate SKILL.md files for consistency and correctness.

Inspired by gstack's gen-skill-docs pattern. Checks that:
- All SKILL.md files have valid frontmatter (name, description)
- Protocol injection lists match actual protocol files
- Agent stubs reference existing skills
- Mode files referenced in SKILL.md actually exist
- Activation rules reference existing skills
- No drift between claude/ and cursor/ shared files

Usage: python3 validate_skill_docs.py [plugin_dir] [--fix] [--json]
  plugin_dir: claude/ or cursor/ directory (default: claude/)
  --fix: auto-fix simple issues (missing protocol refs)
  --json: output as JSON instead of terminal
"""

import json
import os
import re
import sys
from pathlib import Path
from typing import Optional


class ValidationResult:
    def __init__(self):
        self.errors: list = []      # Must fix
        self.warnings: list = []    # Should fix
        self.info: list = []        # Informational
        self.checks_passed: int = 0
        self.checks_total: int = 0

    def error(self, check: str, msg: str, file: str = ""):
        self.errors.append({"check": check, "message": msg, "file": file})
        self.checks_total += 1

    def warn(self, check: str, msg: str, file: str = ""):
        self.warnings.append({"check": check, "message": msg, "file": file})
        self.checks_total += 1

    def ok(self, check: str):
        self.checks_passed += 1
        self.checks_total += 1

    def passed(self) -> bool:
        return len(self.errors) == 0

    def to_dict(self) -> dict:
        return {
            "passed": self.passed(),
            "checks_passed": self.checks_passed,
            "checks_total": self.checks_total,
            "errors": self.errors,
            "warnings": self.warnings,
            "info": self.info,
        }


def check_frontmatter(skill_path: Path, result: ValidationResult):
    """Check SKILL.md has valid frontmatter."""
    text = skill_path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        result.error("frontmatter", f"Missing frontmatter", str(skill_path))
        return

    # Extract frontmatter
    parts = text.split("---", 2)
    if len(parts) < 3:
        result.error("frontmatter", f"Malformed frontmatter (no closing ---)", str(skill_path))
        return

    fm = parts[1]
    if "name:" not in fm:
        result.error("frontmatter", f"Missing 'name' in frontmatter", str(skill_path))
    else:
        result.ok("frontmatter-name")

    if "description:" not in fm:
        result.error("frontmatter", f"Missing 'description' in frontmatter", str(skill_path))
    else:
        result.ok("frontmatter-desc")


def check_protocol_refs(skill_path: Path, protocols_dir: Path, result: ValidationResult):
    """Check that protocol file references in SKILL.md point to existing files."""
    text = skill_path.read_text(encoding="utf-8")
    # Pattern: cat .synaptory/.protocols/FILENAME.md
    refs = re.findall(r'\.synaptory/\.protocols/(\S+\.md)', text)

    # These are runtime protocol files copied to project workspace, not plugin protocols
    # The source protocols are in skills/_shared/protocols/
    for ref in refs:
        proto_path = protocols_dir / ref
        if not proto_path.exists():
            result.warn("protocol-ref", f"References protocol '{ref}' but not found in {protocols_dir}", str(skill_path))
        else:
            result.ok(f"protocol-ref-{ref}")


def check_modes(skill_path: Path, result: ValidationResult):
    """Check that mode files referenced in SKILL.md exist."""
    skill_dir = skill_path.parent
    modes_dir = skill_dir / "modes"
    text = skill_path.read_text(encoding="utf-8")

    # Pattern: read `modes/FILENAME.md`
    mode_refs = re.findall(r'modes/(\S+\.md)', text)
    for mode_ref in mode_refs:
        # Skip template variables like {mode}.md
        if '{' in mode_ref or '$' in mode_ref:
            continue
        mode_path = modes_dir / mode_ref
        if not mode_path.exists():
            result.error("mode-ref", f"References mode '{mode_ref}' but file not found", str(skill_path))
        else:
            result.ok(f"mode-ref-{mode_ref}")

    # Check for orphaned mode files (exist on disk but not referenced)
    if modes_dir.exists():
        for mode_file in modes_dir.glob("*.md"):
            if mode_file.name not in mode_refs and mode_file.name not in text:
                result.warn("orphan-mode", f"Mode file '{mode_file.name}' exists but not referenced in SKILL.md", str(mode_file))


def check_agent_stubs(agents_dir: Path, skills_dir: Path, result: ValidationResult):
    """Check that agent stubs reference existing skills."""
    if not agents_dir.exists():
        result.warn("agents-dir", "No agents/ directory found")
        return

    for agent_file in agents_dir.glob("*.md"):
        text = agent_file.read_text(encoding="utf-8")
        # Check for skill references
        skill_refs = re.findall(r'skills/(\S+)/SKILL\.md', text)
        for skill_ref in skill_refs:
            skill_path = skills_dir / skill_ref / "SKILL.md"
            if not skill_path.exists():
                result.error("agent-skill-ref", f"Agent '{agent_file.name}' references skill '{skill_ref}' but SKILL.md not found", str(agent_file))
            else:
                result.ok(f"agent-skill-{skill_ref}")


def check_activation_rules(plugin_dir: Path, skills_dir: Path, result: ValidationResult):
    """Check activation-rules.json references existing skills."""
    rules_file = skills_dir / "synaptory" / "hooks" / "activation-rules.json"
    if not rules_file.exists():
        result.info.append({"check": "activation-rules", "message": "No activation-rules.json found"})
        return

    try:
        rules = json.loads(rules_file.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        result.error("activation-rules", f"Invalid JSON: {e}", str(rules_file))
        return

    for rule in rules.get("rules", []):
        skill_name = rule.get("skill", "")
        # synaptory is special (it's the orchestrator itself)
        if skill_name == "synaptory":
            continue
        skill_path = skills_dir / skill_name / "SKILL.md"
        if not skill_path.exists():
            result.warn("activation-skill-ref", f"Activation rule references skill '{skill_name}' but SKILL.md not found", str(rules_file))
        else:
            result.ok(f"activation-{skill_name}")


def check_cross_platform_parity(claude_dir: Path, cursor_dir: Path, result: ValidationResult):
    """Check shared files match between claude/ and cursor/."""
    if not cursor_dir.exists():
        result.info.append({"check": "parity", "message": "No cursor/ directory found — skipping parity check"})
        return

    # Check shared protocols
    claude_protos = claude_dir / "skills" / "_shared" / "protocols"
    cursor_protos = cursor_dir / "skills" / "_shared" / "protocols"

    if claude_protos.exists() and cursor_protos.exists():
        claude_files = {f.name for f in claude_protos.glob("*.md")}
        cursor_files = {f.name for f in cursor_protos.glob("*.md")}
        missing_in_cursor = claude_files - cursor_files
        for f in missing_in_cursor:
            result.warn("parity-protocol", f"Protocol '{f}' exists in claude/ but not cursor/", str(claude_protos / f))

    # Check shared scripts
    claude_scripts = claude_dir / "skills" / "_shared" / "scripts"
    cursor_scripts = cursor_dir / "skills" / "_shared" / "scripts"

    if claude_scripts.exists() and cursor_scripts.exists():
        claude_files = {f.name for f in claude_scripts.glob("*.py")}
        cursor_files = {f.name for f in cursor_scripts.glob("*.py")}
        missing_in_cursor = claude_files - cursor_files
        for f in missing_in_cursor:
            result.warn("parity-script", f"Script '{f}' exists in claude/ but not cursor/", str(claude_scripts / f))

    # Check hook lib
    claude_lib = claude_dir / "hooks" / "lib"
    cursor_lib = cursor_dir / "hooks" / "scripts" / "lib"

    if claude_lib.exists() and cursor_lib.exists():
        claude_files = {f.name for f in claude_lib.glob("*.py")}
        cursor_files = {f.name for f in cursor_lib.glob("*.py")}
        missing_in_cursor = claude_files - cursor_files
        for f in missing_in_cursor:
            result.warn("parity-hooklib", f"Hook lib '{f}' exists in claude/ but not cursor/", str(claude_lib / f))


def validate(plugin_dir: Path) -> ValidationResult:
    result = ValidationResult()
    skills_dir = plugin_dir / "skills"
    agents_dir = plugin_dir / "agents"
    protocols_dir = skills_dir / "_shared" / "protocols"

    if not skills_dir.exists():
        result.error("structure", f"No skills/ directory in {plugin_dir}")
        return result

    # Check each SKILL.md
    for skill_md in skills_dir.rglob("SKILL.md"):
        check_frontmatter(skill_md, result)
        check_protocol_refs(skill_md, protocols_dir, result)
        check_modes(skill_md, result)

    # Check agent stubs
    check_agent_stubs(agents_dir, skills_dir, result)

    # Check activation rules
    check_activation_rules(plugin_dir, skills_dir, result)

    # Check cross-platform parity
    repo_root = plugin_dir.parent
    if plugin_dir.name == "claude":
        check_cross_platform_parity(plugin_dir, repo_root / "cursor", result)

    return result


def format_terminal(result: ValidationResult) -> str:
    lines = []
    lines.append("━━━ Skill Doc Validation ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append(f"  Checks: {result.checks_passed}/{result.checks_total} passed")
    lines.append(f"  Errors: {len(result.errors)}  Warnings: {len(result.warnings)}")
    lines.append("")

    if result.errors:
        lines.append("  ERRORS (must fix)")
        lines.append("  ─────────────────────────────────────────────────────────")
        for e in result.errors:
            lines.append(f"  ✗ [{e['check']}] {e['message']}")
            if e.get("file"):
                lines.append(f"    → {e['file']}")
        lines.append("")

    if result.warnings:
        lines.append("  WARNINGS (should fix)")
        lines.append("  ─────────────────────────────────────────────────────────")
        for w in result.warnings:
            lines.append(f"  ⚠ [{w['check']}] {w['message']}")
            if w.get("file"):
                lines.append(f"    → {w['file']}")
        lines.append("")

    if result.info:
        for i in result.info:
            lines.append(f"  ℹ {i['message']}")
        lines.append("")

    status = "PASSED" if result.passed() else "FAILED"
    lines.append(f"  Status: {status}")
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    return "\n".join(lines)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Validate SKILL.md files for consistency")
    parser.add_argument("plugin_dir", nargs="?", default="claude", help="Plugin directory (default: claude)")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--fix", action="store_true", help="Auto-fix simple issues")
    args = parser.parse_args()

    plugin_dir = Path(args.plugin_dir).resolve()
    if not plugin_dir.exists():
        print(f"Error: {plugin_dir} not found", file=sys.stderr)
        sys.exit(1)

    result = validate(plugin_dir)

    if args.json:
        print(json.dumps(result.to_dict(), indent=2))
    else:
        print(format_terminal(result))

    sys.exit(0 if result.passed() else 1)


if __name__ == "__main__":
    main()
