#!/usr/bin/env python3
# GENERATED by plugin-cursor/scripts/compose.sh — edit core/ or plugin-claude/ then re-compose
# Copyright 2024-2026 H3Tech Inc. All rights reserved. PROPRIETARY.
"""synaptory doctor — CLI-session diagnostic.

Auth is owned by the synaptory CLI (SAD: the plugin does not parse access
tokens). This report shells out to `synaptory whoami --check` the same way
SessionStart does.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys

import host_env


def _python_info() -> str:
    v = sys.version_info
    return f"{v.major}.{v.minor}.{v.micro} ({sys.executable})"


def _run_cli(args: list[str]) -> tuple[int | None, str]:
    cli_name = "synaptory-local" if host_env.local_plugin_runtime() else "synaptory"
    override = os.environ.get("SYNAPTORY_CLI_BIN", "").strip()
    cli = override if override and os.path.isfile(override) and os.access(override, os.X_OK) else shutil.which(cli_name)
    if not cli:
        return None, f"{cli_name} CLI not found or build identity does not match this plugin"
    try:
        proc = subprocess.run(
            [cli, *args],
            capture_output=True,
            text=True,
            timeout=20,
            check=False,
        )
        out = ((proc.stdout or "") + (proc.stderr or "")).strip()
        return proc.returncode, out
    except (OSError, subprocess.TimeoutExpired) as exc:
        return 1, str(exc)


def run() -> int:
    lines = [
        "",
        "synaptory doctor",
        "================",
        f"Python:        {_python_info()}",
    ]
    rc, out = _run_cli(["whoami", "--check"])
    if rc is None:
        cli_name = "synaptory-local" if host_env.local_plugin_runtime() else "synaptory"
        lines += [
            "CLI:           NOT FOUND",
            "",
            f"Install the {cli_name} CLI, then run `{cli_name} login`.",
            "Doctor no longer reads plugin access-token files — the CLI is",
            "the only auth path.",
            "",
        ]
        print("\n".join(lines))
        return 1
    lines.append(
        f"whoami --check: {'ok' if rc == 0 else 'FAILED'} (exit {rc})"
    )
    if out:
        lines.append(out)
    if rc != 0:
        cli_name = "synaptory-local" if host_env.local_plugin_runtime() else "synaptory"
        lines += [
            "",
            f"Fix: `{cli_name} login` then re-run doctor.",
            "",
        ]
        print("\n".join(lines))
        return 1
    _, who = _run_cli(["whoami"])
    if who:
        lines.append(who)
    lines += ["", "All checks passed.", ""]
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(run())
