# GENERATED by plugin-cursor/scripts/compose.sh — edit core/ or plugin-claude/ then re-compose
"""The declared path language: one versioned grammar, and its refusals (#644).

`SC-MTH-008` requires every Work Unit to declare the path scope it may address,
and `SC-MTH-010` derives concurrency from those declarations. Both need a
representation a machine can compare, so §5.2 of the replacement requirements
asks for **one versioned, machine-checkable path language** whose unsupported
and ambiguous patterns are **refused rather than guessed**.

This is that language. It is deliberately small, and the smallness is the
design: every form it accepts has exactly one reading, so two people declaring
the same intent produce the same declaration and the comparison below is a fact
rather than an interpretation.

WHAT IT ACCEPTS, and nothing else:

    api/                    a directory prefix -- this directory and everything under it
    api/**                  the same thing, spelled the way a reader expects
    api/routers/auth.py     one exact file

WHAT IT REFUSES, each because it has more than one honest reading:

    *.py            a suffix pattern -- matches in every directory, so it
                    declares no region at all
    **/fixtures     a leading globstar -- same problem, one level down
    api/*/routers   an interior wildcard -- "one segment" is a guess about how
                    deep the tree is
    ../shared       traversal -- a scope that leaves the repository is not a
                    scope in it
    /etc/passwd     absolute -- there is one repository root and the
                    declaration is relative to it
    api\\routers     a backslash -- one separator, so two spellings cannot
                    disagree about the same path
    "" / "   "      empty -- and this one matters most, see below

THE EMPTY CASE IS THE ONE THAT BIT THE PREDECESSOR. `story_pipeline.
_scopes_disjoint` documents that "Empty/blank entries fail closed (overlap)",
and a blank ENTRY does -- while an empty LIST returns True, disjoint from
everything, because the loop never runs. Masked today, because the single
caller rejects a scope-less unit separately and never compares scopes in the
default isolation mode at all. Promoted to an admission condition unchanged, it
would mean a Work Unit admitted with **no** declared scope is concurrent-safe
with everything, which is the exact hole `C-07` exists to refuse. So
`intersects` REFUSES an absent scope before it compares anything, and the
refusal is a raised error rather than a `True`/`False`, because a boolean has
nowhere to put "you did not declare one".

CASE SENSITIVITY IS NOT NORMALISED, and that is a decision rather than an
omission. macOS is case-insensitive and Linux is not, so `Api/` and `api/`
are one path on a laptop and two in CI. Folding case would make a declaration
mean different things on different machines; refusing to fold it means a
collision that only exists on macOS is reported as a collision everywhere,
which is the safe direction. `same_path_different_case` says so explicitly
where a caller needs to know.

A RENAME TOUCHES BOTH PATHS. `changed_paths` takes the old and the new name of
a renamed file, because a unit whose scope covers only the destination has
still modified the source, and a scope check that sees one of the two lets a
rename move a file out of somebody else's region unremarked.
"""

from __future__ import annotations

from typing import Iterable, List, Sequence, Set, Tuple

#: The grammar's version. It travels in the sealed declaration, so a Cycle
#: admitted under one version is never re-read under another's rules.
GRAMMAR_VERSION = "1"

#: The forms above, for a refusal that tells the caller what to write instead.
SUPPORTED = (
    "api/                  a directory and everything under it",
    "api/**                the same, spelled explicitly",
    "api/routers/auth.py   one exact file",
)


class PathScopeError(ValueError):
    """A declaration this grammar refuses, with the reason and the alternative."""


def _refuse(entry: object, why: str) -> "PathScopeError":
    return PathScopeError(
        "path scope %r is refused: %s\nSupported forms (grammar v%s):\n  %s"
        % (entry, why, GRAMMAR_VERSION, "\n  ".join(SUPPORTED))
    )


def normalize(entry: object) -> str:
    """One declaration to its canonical form, or a refusal.

    A directory prefix normalises to a trailing slash and an exact file to
    itself, so the two are distinguishable afterwards without re-parsing:
    `api/` stays `api/`, and `api/x.py` stays `api/x.py`.
    """
    if not isinstance(entry, str):
        raise _refuse(entry, "a path scope is a string")
    raw = entry.strip()
    if not raw:
        raise _refuse(entry, "it is empty, and an empty scope declares nothing")
    if "\\" in raw:
        raise _refuse(entry, "it uses a backslash; this grammar has one separator")
    if raw.startswith("/") or (len(raw) > 1 and raw[1] == ":"):
        raise _refuse(entry, "it is absolute; declarations are repository-relative")
    if raw.startswith("~"):
        raise _refuse(entry, "it names a home directory, not a path in this repository")
    segments = raw.split("/")
    if any(seg in ("..", ".") for seg in segments):
        raise _refuse(entry, "it traverses; a scope that leaves the repository is not one")
    if "" in segments[:-1]:
        raise _refuse(entry, "it has an empty path segment")

    if raw.endswith("/**"):
        body = raw[: -len("/**")]
        if not body:
            raise _refuse(entry, "`/**` alone is the whole repository, which no unit may declare")
        if "*" in body:
            raise _refuse(entry, "a wildcard before the trailing `/**` has no single reading")
        return body.rstrip("/") + "/"
    if raw.endswith("/"):
        body = raw[:-1]
        if not body or "*" in body:
            raise _refuse(entry, "a wildcard in a directory prefix has no single reading")
        return body + "/"
    if "*" in raw:
        raise _refuse(
            entry,
            "a wildcard is accepted only as a trailing `/**`; `*.py` and `**/x` "
            "match in every directory and so declare no region",
        )
    return raw


def normalize_all(entries: Iterable[object]) -> List[str]:
    """A whole declaration, refusing on the first entry the grammar rejects.

    Order is preserved and duplicates are kept: a declaration is a record of
    what somebody wrote, and silently de-duplicating it makes the sealed
    document differ from the one they reviewed.
    """
    return [normalize(entry) for entry in entries]


def _prefix_of(scope: str) -> Tuple[str, bool]:
    """(comparable prefix, is_directory)."""
    if scope.endswith("/"):
        return scope[:-1], True
    return scope, False


def _pair_intersects(left: str, right: str) -> bool:
    """A prefix relationship is a collision, whichever side declared a directory.

    The subtle case, and the reason this does not consult `is_directory`: a
    declaration without a trailing slash is an exact path, and `api` may still
    be a DIRECTORY on disk. Reading it strictly would make `api` and
    `api/routers/` disjoint, both units would dispatch, and the collision would
    surface at merge -- which §7.2 says is not recoverable from evidence
    afterwards.

    So ambiguity resolves to the BROADER reading. Over-refusing is recoverable:
    the author declares more precisely and proceeds. Under-refusing is not.
    The cost is a false collision between an exact file and a path beneath it
    (`api/x.py` vs `api/x.py/y`), which cannot exist on a filesystem.

    `covers` keeps the strict reading, because validating the change that
    actually shipped is a different question with a different safe direction.
    """
    a, _ = _prefix_of(left)
    b, _ = _prefix_of(right)
    if a == b:
        return True
    return b.startswith(a + "/") or a.startswith(b + "/")


def intersects(left: Sequence[object], right: Sequence[object]) -> bool:
    """Do two declared scopes address any common path?

    Compares DECLARATIONS, not the files that happen to exist: creating a new
    file cannot escape a scope that was already accepted, which a
    filesystem-walking check would allow.

    Raises rather than answers when either side declared nothing, because
    "these do not overlap" and "one of them did not say" are different facts
    and only the first is safe to act on.
    """
    if not left or not right:
        raise PathScopeError(
            "cannot compare an absent path scope: a Work Unit that declares no "
            "scope is refused at admission, not treated as disjoint from "
            "everything. `SC-MTH-008` requires the declaration; this is where "
            "its absence stops being silent."
        )
    a = normalize_all(left)
    b = normalize_all(right)
    return any(_pair_intersects(x, y) for x in a for y in b)


def covers(scope: Sequence[object], path: object) -> bool:
    """Is one changed path inside a declared scope?"""
    candidate = normalize(path) if not str(path).endswith("/") else normalize(path)
    target, _ = _prefix_of(candidate)
    for entry in normalize_all(scope):
        prefix, is_dir = _prefix_of(entry)
        if target == prefix or (is_dir and target.startswith(prefix + "/")):
            return True
    return False


def uncovered(scope: Sequence[object], changed_paths: Iterable[object]) -> List[str]:
    """Which changed paths fall outside the declaration.

    This is the check that runs before a candidate is promoted: a declaration
    accepted at admission is worth nothing if the change that ships was not
    compared against it.

    A renamed file supplies BOTH names -- see the module docstring.
    """
    outside: List[str] = []
    for path in changed_paths:
        if not covers(scope, path):
            outside.append(normalize(path))
    return outside


def same_path_different_case(left: object, right: object) -> bool:
    """True when two declarations differ only by case.

    Not folded automatically. A caller that wants the macOS reading asks; a
    caller that does not gets the Linux one, which is the stricter of the two.
    """
    a, b = normalize(left), normalize(right)
    return a != b and a.lower() == b.lower()


def owners_of(shared_path: object, owners: Sequence[Tuple[object, object]]) -> Set[str]:
    """Which Work Units claim one shared path.

    `SC-MTH-008` wants exactly one -- never none, never two -- so the caller
    needs the SET rather than a boolean: "none" and "two" are different
    refusals and a barrier has to name which one it hit.
    """
    claimed = set()
    for unit_id, scope in owners:
        entries = scope if isinstance(scope, (list, tuple)) else [scope]
        if covers(entries, shared_path):
            claimed.add(str(unit_id))
    return claimed
