#!/usr/bin/env python3
# GENERATED by plugin-cursor/scripts/compose.sh — edit core/ or plugin-claude/ then re-compose
"""Asset-exhaustive preview smoke check for synaptory hooks.

Field incident (issue #134 GAP-9): a sprint-review preview deploy used
`cp -r ... 2>/dev/null` that silently dropped Next.js standalone
`.next/static`, and the smoke test only checked `GET / == 200` — which
passes even when every stylesheet and script 400s. The stakeholder saw
an unstyled page despite nine green QE receipts.

This module replaces root-only curls with an asset-exhaustive gate: it
fetches each route's HTML, extracts every same-origin asset reference
(scripts, stylesheets, icons, preloads, images, srcset candidates,
media sources, og:image), follows stylesheets one level deep into
`url(...)` and `@import` references, and GETs every unique asset. Any
non-2xx response or network error is a failure.

Stdlib-only (NFR-PLUGIN-2: Python 3.9+). No external network in any
default path — intended for localhost dev/preview servers.

CLI:
    python3 preview_asset_check.py <base_url> [route ...] \
        [--timeout N] [--max-assets N]

Output: a single JSON object on stdout:
    {
      "base_url": ...,
      "routes": [...],
      "assets_checked": N,
      "failures": [{"url": ..., "status": int | "error: <msg>",
                    "referrer": ...}],
      "truncated": bool,
      "passed": bool
    }
Exit 0 iff passed (every route HTML fetch and every asset check
succeeded AND the asset set was not truncated by --max-assets); exit 1
otherwise. A route fetch failure is itself a failure entry, and a
truncated run fails closed (unchecked assets cannot be asserted 200).
"""

# NFR-PLUGIN-2: Python 3.9+. Annotations below use PEP 604 unions
# (`X | None`); the future-import defers evaluation so 3.9 doesn't
# choke at module-load time.
from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from html.parser import HTMLParser
from typing import Any

DEFAULT_TIMEOUT = 10  # seconds per HTTP request
DEFAULT_MAX_ASSETS = 500  # safety cap on unique assets checked
USER_AGENT = "synaptory-preview-asset-check/1.0"

# Reference schemes/prefixes that are never fetchable assets.
_SKIP_PREFIXES = ("data:", "mailto:", "javascript:", "tel:", "blob:", "about:")

# url(...) inside CSS — group 2 is the target (quotes optional).
_CSS_URL_RE = re.compile(r"""url\(\s*(['"]?)([^'")]+)\1\s*\)""", re.IGNORECASE)
# @import "x.css" / @import 'x.css' (the url(...) form is caught by _CSS_URL_RE,
# but we scan the @import statement to know the target should be treated as CSS).
_CSS_IMPORT_RE = re.compile(
    r"""@import\s+(?:url\(\s*)?(['"]?)([^'")\s;]+)\1""", re.IGNORECASE
)


class _AssetExtractor(HTMLParser):
    """Collect raw asset references from an HTML document.

    Populates two lists of raw (unresolved) reference strings:
      * ``refs`` — plain asset references (script src, img src/srcset, ...).
      * ``stylesheet_refs`` — link rel=stylesheet hrefs (parsed as CSS later).
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.refs: list[str] = []
        self.stylesheet_refs: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        a = {k: (v or "") for k, v in attrs}
        if tag == "script" and a.get("src"):
            self.refs.append(a["src"])
        elif tag == "link" and a.get("href"):
            rel = a.get("rel", "").lower().split()
            if "stylesheet" in rel:
                self.stylesheet_refs.append(a["href"])
            else:
                # Any other rel — icon, preload, modulepreload, manifest, ...
                self.refs.append(a["href"])
        elif tag in ("img", "source"):
            if a.get("src"):
                self.refs.append(a["src"])
            if a.get("srcset"):
                self.refs.extend(_parse_srcset(a["srcset"]))
        elif tag in ("video", "audio"):
            if a.get("src"):
                self.refs.append(a["src"])
        elif tag == "meta":
            if a.get("property", "").lower() == "og:image" and a.get("content"):
                self.refs.append(a["content"])

    # <source> and <img> may appear self-closed in JSX-flavored output.
    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.handle_starttag(tag, attrs)


def _parse_srcset(srcset: str) -> list[str]:
    """Split a srcset attribute into candidate URLs.

    Each comma-separated candidate is `<url> [descriptor]`; the URL is the
    first whitespace-delimited token.
    """
    urls: list[str] = []
    for candidate in srcset.split(","):
        candidate = candidate.strip()
        if not candidate:
            continue
        urls.append(candidate.split()[0])
    return urls


def _extract_css_refs(css_text: str) -> tuple[list[str], list[str]]:
    """Return (plain_refs, import_refs) from a CSS body.

    ``import_refs`` are @import targets (candidate CSS for one more parse
    level); ``plain_refs`` are url(...) targets not part of an @import.
    """
    import_refs = [m.group(2) for m in _CSS_IMPORT_RE.finditer(css_text)]
    import_set = set(import_refs)
    plain_refs = [
        m.group(2)
        for m in _CSS_URL_RE.finditer(css_text)
        if m.group(2) not in import_set
    ]
    return plain_refs, import_refs


def _should_skip(ref: str) -> bool:
    """True for refs that are never fetchable same-origin assets."""
    ref = ref.strip()
    if not ref or ref.startswith("#"):
        return True
    return ref.lower().startswith(_SKIP_PREFIXES)


def _same_origin(url: str, base_url: str) -> bool:
    a = urllib.parse.urlsplit(url)
    b = urllib.parse.urlsplit(base_url)
    return (a.scheme, a.netloc) == (b.scheme, b.netloc)


def _fetch(url: str, timeout: float) -> tuple[int | str, bytes, str]:
    """GET a URL (following redirects). Returns (status, body, final_url).

    ``status`` is the int HTTP status when a response was received (including
    4xx/5xx), or an ``"error: <msg>"`` string for network-level failures.
    GET, not HEAD — some dev servers mishandle HEAD (issue #134).
    """
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status, resp.read(), resp.geturl()
    except urllib.error.HTTPError as e:
        return e.code, b"", url
    except Exception as e:  # URLError, timeout, ConnectionError, ...
        return f"error: {e}", b"", url


def _decode(body: bytes) -> str:
    return body.decode("utf-8", errors="replace")


def check_preview_assets(
    base_url: str,
    routes: list[str] | None = None,
    timeout: float = DEFAULT_TIMEOUT,
    max_assets: int = DEFAULT_MAX_ASSETS,
) -> dict[str, Any]:
    """Fetch each route's HTML and every same-origin asset it references.

    Returns the result dict described in the module docstring. ``passed``
    is True iff every route fetched 2xx and every unique asset fetched 2xx.
    """
    routes = list(routes) if routes else ["/"]
    base_url = base_url.rstrip("/")

    failures: list[dict[str, Any]] = []
    # Worklist of (url, referrer, kind, css_depth). kind: "asset" | "css".
    # Direct stylesheets are css_depth=0; their @import targets are parsed
    # once more (depth 1); nothing deeper is parsed, only fetched.
    queue: list[tuple[str, str, str, int]] = []
    seen: set[str] = set()
    truncated = False

    def enqueue(ref: str, resolve_base: str, referrer: str, kind: str, depth: int) -> None:
        nonlocal truncated
        if _should_skip(ref):
            return
        resolved = urllib.parse.urljoin(resolve_base, ref.strip())
        resolved, _frag = urllib.parse.urldefrag(resolved)
        if not resolved or not _same_origin(resolved, base_url):
            return
        if resolved in seen:
            return
        if len(seen) >= max_assets:
            truncated = True
            return
        seen.add(resolved)
        queue.append((resolved, referrer, kind, depth))

    routes_fetched = 0
    for route in routes:
        route_url = base_url + (route if route.startswith("/") else "/" + route)
        status, body, doc_url = _fetch(route_url, timeout)
        if not (isinstance(status, int) and 200 <= status < 300):
            failures.append({"url": route_url, "status": status, "referrer": None})
            continue
        routes_fetched += 1
        parser = _AssetExtractor()
        try:
            parser.feed(_decode(body))
            parser.close()
        except Exception as e:  # never let a malformed doc crash the gate
            failures.append(
                {"url": route_url, "status": f"error: html parse: {e}", "referrer": None}
            )
            continue
        for ref in parser.refs:
            enqueue(ref, doc_url, doc_url, "asset", 0)
        for ref in parser.stylesheet_refs:
            enqueue(ref, doc_url, doc_url, "css", 0)

    assets_checked = 0
    i = 0
    while i < len(queue):
        url, referrer, kind, depth = queue[i]
        i += 1
        status, body, final_url = _fetch(url, timeout)
        assets_checked += 1
        ok = isinstance(status, int) and 200 <= status < 300
        if not ok:
            failures.append({"url": url, "status": status, "referrer": referrer})
            continue
        if kind == "css":
            plain_refs, import_refs = _extract_css_refs(_decode(body))
            for ref in plain_refs:
                enqueue(ref, final_url, url, "asset", depth)
            for ref in import_refs:
                # Parse @import'd CSS once (depth 0 -> 1); beyond that,
                # fetch-only — no recursion.
                next_kind = "css" if depth == 0 else "asset"
                enqueue(ref, final_url, url, next_kind, depth + 1)

    result: dict[str, Any] = {
        "base_url": base_url,
        "routes": routes,
        "assets_checked": assets_checked,
        "failures": failures,
        # Fail closed on truncation (#170 review): once the asset set exceeds
        # --max-assets, unchecked assets remain — including, potentially, a
        # missing stylesheet — so the exhaustive gate MUST NOT report a pass.
        # The gate's whole point is "every referenced asset is 200"; a
        # truncated run cannot assert that.
        "truncated": truncated,
        "passed": not failures and routes_fetched == len(routes) and not truncated,
    }
    if truncated:
        result["warning"] = (
            f"asset count exceeded --max-assets={max_assets}; "
            f"only the first {max_assets} unique assets were checked — the gate "
            f"fails closed. Re-run with a higher --max-assets to cover them all."
        )
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Asset-exhaustive preview smoke check: fetch route HTML and "
            "verify every same-origin asset it references returns 2xx."
        )
    )
    parser.add_argument("base_url", help="Preview base URL, e.g. http://localhost:3000")
    parser.add_argument(
        "routes", nargs="*", default=None, help="Routes to check (default: /)"
    )
    parser.add_argument(
        "--timeout", type=float, default=DEFAULT_TIMEOUT,
        help=f"Per-request timeout in seconds (default {DEFAULT_TIMEOUT})",
    )
    parser.add_argument(
        "--max-assets", type=int, default=DEFAULT_MAX_ASSETS,
        help=f"Safety cap on unique assets checked (default {DEFAULT_MAX_ASSETS})",
    )
    args = parser.parse_args(argv)

    result = check_preview_assets(
        args.base_url,
        routes=args.routes or ["/"],
        timeout=args.timeout,
        max_assets=args.max_assets,
    )
    print(json.dumps(result, indent=2))
    return 0 if result["passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
