#!/usr/bin/env python3
# GENERATED by plugin-cursor/scripts/compose.sh — edit core/ or plugin-claude/ then re-compose
"""Fail-closed protocol materialization for every host.

Expanded SKILL.md bodies `!cat` `.synaptory/.protocols/<name>.md`. Dist
packages ship no on-disk `skills/_shared/protocols/` fallback (ADR-016), so
an empty `skills get` must refuse the session rather than leave agents with
zero protocol context.

Python 3.9 compatible: this file is projected into every host package.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Callable, List, Optional

# Keep in sync with plugin-claude/hooks/synaptory-inject-protocols.sh
# (the 17 injected into subagent context) plus every live
# `.synaptory/.protocols/<name>.md` reference in shipped workflows.
# Dist packages have no on-disk fallback (ADR-016).
REQUIRED_PROTOCOLS = (
    "receipt-protocol",
    "input-validation",
    "tool-efficiency",
    "freshness-protocol",
    "iron-laws",
    "verification-discipline",
    "socratic-gate",
    "anti-safe-harbor",
    "script-output-handling",
    "clean-code-self-check",
    "scope-challenge",
    "finding-memory",
    "tdd-discipline",
    "code-review-response",
    "subagent-isolation",
    "source-attribution",
    "open-decision-registry",
    "ux-protocol",
    "visual-identity",
    "boundary-safety",
    "conflict-resolution",
    "coverage-ratchet",
    "ephemeral-environments",
    "local-deploy-verification",
    "design-grooming",
    "sa-triggers",
)
PROTOCOL_NAMES = REQUIRED_PROTOCOLS

_PROTOCOL_FETCH_BUDGET_S = 6.0
_PROTOCOL_FETCH_ONE_S = 4.0


def protocol_disk_dirs(plugin_root: Path, host: str = "claude") -> List[Path]:
    dirs = [Path(plugin_root) / "skills" / "_shared" / "protocols"]
    if host == "cursor":
        sibling = Path(plugin_root).parent / "plugin-claude" / "skills" / "_shared" / "protocols"
        if sibling not in dirs:
            dirs.append(sibling)
    return dirs


def _read_protocol_disk(name: str, disk_dirs: List[Path]) -> str:
    for d in disk_dirs:
        path = d / ("%s.md" % name)
        if path.is_file():
            try:
                return path.read_text(encoding="utf-8")
            except OSError:
                return ""
    return ""


def _fetch_protocol_body(
    name: str,
    cli: Optional[str],
    disk_dirs: List[Path],
    host: str,
) -> str:
    body = ""
    if cli:
        cmd = [cli, "skills", "get", "protocols/%s" % name]
        if host == "cursor":
            cmd.extend(["--host", "cursor"])
        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=False,
                timeout=_PROTOCOL_FETCH_ONE_S,
            )
        except (OSError, subprocess.TimeoutExpired):
            proc = None
        if proc is not None and proc.returncode == 0 and proc.stdout.strip():
            body = proc.stdout
    if not body:
        body = _read_protocol_disk(name, disk_dirs)
    return body


def materialize_protocols(
    project: str,
    *,
    plugin_root: Path,
    cli: Optional[str] = None,
    host: str = "claude",
    fetch_one: Optional[Callable[[str], str]] = None,
) -> List[str]:
    """Write protocol bodies to `.synaptory/.protocols/<name>.md` in parallel.

    Returns names that are still missing (empty = success). Callers must
    refuse when the list is non-empty: dist packages have no on-disk
    protocol fallback.
    """
    dest = Path(project) / ".synaptory" / ".protocols"
    try:
        dest.mkdir(parents=True, exist_ok=True)
    except OSError:
        return list(REQUIRED_PROTOCOLS)
    disk_dirs = protocol_disk_dirs(Path(plugin_root), host)
    missing: List[str] = []
    need_fetch: List[str] = []
    for name in PROTOCOL_NAMES:
        cached = dest / ("%s.md" % name)
        if cached.is_file() and cached.stat().st_size > 0:
            continue
        need_fetch.append(name)
    deadline = time.monotonic() + _PROTOCOL_FETCH_BUDGET_S
    if need_fetch:
        workers = min(8, len(need_fetch))
        with ThreadPoolExecutor(max_workers=workers) as pool:
            futs = {
                pool.submit(
                    fetch_one if fetch_one is not None else _fetch_protocol_body,
                    name,
                    *(() if fetch_one is not None else (cli, disk_dirs, host)),
                ): name
                for name in need_fetch
            }
            try:
                remaining = max(0.05, deadline - time.monotonic())
                for fut in as_completed(futs, timeout=remaining):
                    name = futs[fut]
                    try:
                        body = fut.result()
                    except Exception:
                        body = ""
                    if (body or "").strip():
                        try:
                            (dest / ("%s.md" % name)).write_text(body, encoding="utf-8")
                        except OSError:
                            body = ""
                    if name in REQUIRED_PROTOCOLS and not (body or "").strip():
                        missing.append(name)
            except TimeoutError:
                for name in need_fetch:
                    path = dest / ("%s.md" % name)
                    if name in REQUIRED_PROTOCOLS and not (
                        path.is_file() and path.stat().st_size > 0
                    ):
                        if name not in missing:
                            missing.append(name)
    for name in PROTOCOL_NAMES:
        path = dest / ("%s.md" % name)
        if name in REQUIRED_PROTOCOLS and not (
            path.is_file() and path.stat().st_size > 0
        ):
            if name not in missing:
                missing.append(name)
    return missing


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", required=True)
    parser.add_argument("--plugin-root", required=True)
    parser.add_argument("--cli", default="")
    parser.add_argument(
        "--host",
        default="claude",
        choices=("claude", "cursor", "codex"),
    )
    args = parser.parse_args(argv)
    cli = (args.cli or "").strip() or None
    missing = materialize_protocols(
        args.project,
        plugin_root=Path(args.plugin_root),
        cli=cli,
        host=args.host,
    )
    if missing:
        sys.stderr.write(
            "synaptory: required protocol bodies were not written to "
            ".synaptory/.protocols/ (%s)\n" % ", ".join(missing)
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
