#!/usr/bin/env python3
# GENERATED by plugin-cursor/scripts/compose.sh — edit core/ or plugin-claude/ then re-compose
# Copyright (c) 2024-2026 H3Tech Inc. All rights reserved. PROPRIETARY.
"""Runtime-federation contracts: the dispatch envelope, attempt identity,
supervision events, and adapter profiles (Epic #339, ticket #341), plus the
capability-profile pilot's vocabulary: the bidirectional role-alias surface,
the receipt-overlay `accountable_role`, typed evidence classes, and the
`criteria_gap_declared` DoD result shape (Epic #410, ticket #399).

Sources of truth: docs/proposals/governed-runtime-pilot.md r3+ (schemas in
section 4, vocabulary notes in 4.4) for the pilot-1 surfaces, and
docs/proposals/capability-profile-pilot.md r2 (3.1 for the alias surface and
accountable_role, 3.3 for evidence classes and the criteria gap) for the
pilot-2 vocabulary. Where this module and those documents disagree, the
document wins and this module gets corrected.

This lives in core/lib rather than the proposal's provisional `core/runtime/`
package because composition already ships core/lib to every host (Claude via
symlink, Cursor and Codex via compose.py); a new top-level core directory
would need compose and build changes on two hosts before the first consumer
existed. The proposal's change map is amended to match (r4).

Validation is hand-rolled in the spq_manifest.py idiom: no jsonschema
dependency, defensive coercion, and every rule returns a message naming the
field so a refusal is actionable. Validators return a list of problems; an
empty list is a pass. Nothing here signs or stores anything: the kernel mints
and binds (ticket #344), the CP coordinates (#350), the bridge executes
(#345). This module only defines what a well-formed object IS.
"""

from __future__ import annotations

import os
import posixpath
import re
from typing import Any, Dict, List, Optional, Sequence, Tuple

SCHEMA_VERSION = 1

ENVELOPE_KIND = "synaptory.dispatch.envelope"

# The pilot's placements. "managed-server" and "provider-managed" are Platform
# waves, deliberately absent: an envelope naming one must be refused, not
# forwarded (proposal 3.4: managed-laptop is a V1-only placement).
PLACEMENTS = ("local", "managed-laptop")

RUNTIME_FAMILIES = ("claude-code", "codex", "cursor-agent")

SELECTION_MODES = ("auto", "prefer", "pin")

# Platform vocabulary carried alongside V1's roster (spec 0.13.0). Capability
# profiles are intent labels for skill composition and grant nothing
# (SC-MTH-004); stage profiles are where Platform obligations attach
# (SP-WRK-022). V1 dispatches roles; these two fields are the evidence overlay
# that lets the same receipt be read in Platform terms.
CAPABILITY_PROFILES = ("analyst", "planner", "producer", "prover")

STAGE_PROFILES = (
    "admitting",
    "analysing",
    "planning",
    "producing",
    "verifying",
    "releasing",
    "operating",
)

# Dispatch-time projection of the nine-agent roster onto the four profiles.
# Three agents straddle profiles in the SPQ design (6.3): po spans analyst and
# planner, pe spans planner and producer, qe spans planner and prover. A
# dispatch is one bounded act, so the straddle resolves to the profile of the
# act being dispatched (a qe dispatch verifies; its planning half happens
# inside po/sa ceremonies). The straddles themselves are research output and
# are recorded as MethodSignals by the ceremonies, not here.
DISPATCH_CAPABILITY_PROFILE = {
    "se": "producer",
    "qe": "prover",
    "cr": "prover",
    "ce": "prover",
    "pe": "producer",
    "tw": "producer",
    "po": "planner",
    "sa": "planner",
    "ra": "analyst",
}

DISPATCH_STAGE_PROFILE = {
    "se": "producing",
    "qe": "verifying",
    "cr": "verifying",
    "ce": "verifying",
    "pe": "producing",
    "tw": "producing",
    "po": "planning",
    "sa": "planning",
    "ra": "analysing",
}

# The nine legacy role names, abbrev -> full agent name. This module is the
# dependency leaf of core/lib (runtime_selector imports it, and since #402 so
# does advance_kernel, which keys its transition expectations on the tables
# above), so this is now the ONLY copy: #402 replaced the kernel's literal
# with a re-export of this table. The byte-identical mirror the Layer-1 test
# used to police is gone, and with it the thing it could drift from.
ROLE_NAMES: Dict[str, str] = {
    "se": "software-engineer",
    "qe": "quality-engineer",
    "cr": "code-reviewer",
    "ce": "compliance-engineer",
    "pe": "platform-engineer",
    "po": "project-owner",
    "sa": "solution-architect",
    "tw": "technical-writer",
    "ra": "research-advisor",
}

_ROLE_ABBREV_BY_NAME: Dict[str, str] = {
    name: abbrev for abbrev, name in ROLE_NAMES.items()
}

# Receipt-overlay field name (pilot 2, #399). The wire keeps `agent:` (the
# #198 rename precedent: renaming a wire value is its own migration campaign);
# `accountable_role` is the Platform-facing accountability label riding
# alongside it (SP-AUT-008: roles confer accountability only, never
# permissions). Soft-required for pipeline receipts during the migration
# window, mirroring the #342 overlay pattern: validated against the alias
# table WHEN PRESENT, absence is a kernel-side warning and never a validator
# failure. Requiring presence is a deliberate later tightening.
ACCOUNTABLE_ROLE = "accountable_role"


def _resolve_role_abbrev(role: Any) -> Optional[str]:
    """The role abbrev for either spelling of a legacy role name, or None."""
    key = str(role or "").strip().lower()
    if key in ROLE_NAMES:
        return key
    return _ROLE_ABBREV_BY_NAME.get(key)


def profile_pair_for_role(role: Any) -> Tuple[str, str]:
    """The `(stage_profile, capability_profile)` pair a legacy role name
    projects onto at dispatch time. Accepts both spellings: the receipt
    abbrev ("se") and the full agent name ("software-engineer").

    This is the single alias surface the pilot allows the nine names to
    survive through (capability-profile-pilot.md 3.1): dispatch and advance
    key on the pair; the names stay wire-compatible aliases. Built on the
    DISPATCH_* projection tables above, never a second copy of them.

    Raises ValueError for a name outside the table, naming both accepted
    spellings, so a typo is refused with a route to the fix rather than
    silently projected onto nothing. Also ValueError -- not KeyError -- when
    the name IS a legacy role but one of the projection tables has no row for
    it: an incomplete projection is a table bug, and #402 made the kernel's
    gate depend on this call, so it has to fail in the shape callers already
    handle rather than as an unhandled lookup.
    """
    abbrev = _resolve_role_abbrev(role)
    if abbrev is None:
        raise ValueError(
            "role: %r is not a legacy role name; expected a role abbrev in "
            "%s or a full agent name in %s"
            % (role, sorted(ROLE_NAMES), sorted(ROLE_NAMES.values()))
        )
    stage_profile = DISPATCH_STAGE_PROFILE.get(abbrev)
    capability_profile = DISPATCH_CAPABILITY_PROFILE.get(abbrev)
    if stage_profile is None or capability_profile is None:
        raise ValueError(
            "role: %r has an incomplete dispatch projection (stage_profile=%r, "
            "capability_profile=%r); both tables must carry every role in %s"
            % (role, stage_profile, capability_profile, sorted(ROLE_NAMES))
        )
    return (stage_profile, capability_profile)


def roles_for_profile_pair(stage_profile: Any, capability_profile: Any) -> Tuple[str, ...]:
    """The role abbrevs that project onto `(stage_profile, capability_profile)`,
    sorted, possibly empty: a valid pair no role projects onto (for example
    admitting/analyst) returns () because the projection is total over roles,
    not over pairs.

    Raises ValueError when either profile is outside its vocabulary: a typo'd
    profile silently yielding () would read as "no roles here" instead of
    "that profile does not exist".
    """
    stage_key = str(stage_profile or "").strip().lower()
    capability_key = str(capability_profile or "").strip().lower()
    if stage_key not in STAGE_PROFILES:
        raise ValueError(
            "stage_profile: %r not in %r" % (stage_profile, STAGE_PROFILES)
        )
    if capability_key not in CAPABILITY_PROFILES:
        raise ValueError(
            "capability_profile: %r not in %r"
            % (capability_profile, CAPABILITY_PROFILES)
        )
    return tuple(
        abbrev
        for abbrev in sorted(DISPATCH_CAPABILITY_PROFILE)
        if DISPATCH_STAGE_PROFILE[abbrev] == stage_key
        and DISPATCH_CAPABILITY_PROFILE[abbrev] == capability_key
    )


def _accountable_role_problems(value: Any) -> List[str]:
    """Problems with an accountable_role value that IS present. Absence is
    never a problem here: the field is soft-required during the migration
    window (the #342 overlay pattern), so only a value outside the alias
    table refuses."""
    if not isinstance(value, str) or _resolve_role_abbrev(value) is None:
        return [
            "accountable_role: %r is not in the role-alias table (accepted: "
            "role abbrevs %s or full agent names %s); the field is "
            "soft-required during the migration window, so omit it rather "
            "than guessing a value"
            % (value, sorted(ROLE_NAMES), sorted(ROLE_NAMES.values()))
        ]
    return []

# Attempt lifecycle. An attempt never re-enters a prior state; the CP enforces
# the transition table (#350), this module only names the vocabulary.
ATTEMPT_STATES = (
    "pending",
    "claimed",
    "running",
    "completed",
    "failed",
    "cancelled",
    "expired",
)

TERMINAL_ATTEMPT_STATES = frozenset({"completed", "failed", "cancelled", "expired"})

#: In the vocabulary so a runner can RECORD "I do not know yet" locally, and
#: refused as a CLOSING value. SP-INT-017: a failure that closes unclassified
#: converts a knowable cause into a permanent unknown, and the receipt is the
#: durable record of a close, so it may not carry it either (proposal 11,
#: "Failure classification").
UNCLASSIFIED_FAILURE = "unclassified"

#: The only location scheme a `config_refs` value may use. It names a path in
#: the MATERIALIZED tree (proposal 6: "how to find `.synaptory.yaml` in the
#: checked-out tree"), which is content the envelope already pins through
#: `source_revision`. Any other scheme or an absolute host path would let a
#: runtime read its configuration from somewhere the dispatch does not pin,
#: and a host runtime's own conversation, memory, hook or session store is
#: exactly what lives at such a path.
CONFIG_REF_SCHEME = "repo://"

# ── the bridge's attempt record, as a host may trust it ──────────────────────

# What an attempt record must agree with the envelope about before anything it
# reports may be projected onto the board. All four, because the useful lie is
# a partial one: a record that names the right story and role but a different
# attempt is exactly the shape that made a superseded generation look current.
ATTEMPT_RECORD_IDENTITY = ("attempt_id", "dispatch_id", "story_id", "role")


def attempt_record_disagreements(envelope: Any, attempt: Any) -> List[str]:
    """Why this attempt record does not describe the requested envelope.

    A host asks the bridge to run one envelope and reads a record back. The
    two are separate documents from separate processes, and the record is
    whatever the bridge printed, so the host must establish that they name the
    same work before it projects the record's generation and state onto the
    dispatch binding.

    The first version of that caller took `fencing_token` and `state` from the
    record but `attempt_id`, story and role from the ENVELOPE, which relabelled
    whatever the bridge reported as the requested attempt and neutralised the
    kernel's exact-attempt guard: supply envelope A, return a record for B, and
    B's generation landed on A's binding (#396).

    ABSENCE IS NOT A MATCH. A record that omits a field cannot establish that
    it names this work, so a missing value is a disagreement rather than a
    waiver -- the same rule the kernel applies to a binding with no attempt id.
    """
    if not isinstance(envelope, dict):
        return ["no envelope to compare the attempt record against"]
    if not isinstance(attempt, dict):
        return ["the bridge reported no attempt record"]
    problems: List[str] = []
    for field in ATTEMPT_RECORD_IDENTITY:
        want = str(envelope.get(field) or "").strip()
        got = str(attempt.get(field) or "").strip()
        if not want:
            problems.append(
                "the envelope names no %s, so nothing here can confirm the "
                "attempt record describes it" % field
            )
            continue
        if not got:
            problems.append(
                "the attempt record reports no %s, so it cannot be confirmed "
                "as the record for %s" % (field, want)
            )
            continue
        if got != want:
            problems.append(
                "the attempt record reports %s %s but the envelope requested "
                "%s" % (field, got, want)
            )
    return problems


def attempt_close_confirmed(attempt: Any) -> bool:
    """Whether the control plane confirmed this attempt's terminal close.

    An attempt record's `state` is what the process decided locally. It is not
    evidence that the control plane accepted it, and the two diverge exactly
    when it matters: a holder fenced out mid-run, or one asked to cancel, can
    still finish its adapter and describe itself as `completed` while the
    control plane has already given the attempt to someone else. Only the
    fenced close (or the fenced cancel acknowledgement) settles it, so the
    record carries that bit and a projection reads this rather than the state.

    `is True` on purpose: a JSON string is truthy, and `"false"` reading as
    confirmed is the same class of bug as a snapshot's `available: "false"`
    selecting a runtime.
    """
    return isinstance(attempt, dict) and attempt.get("cp_closed") is True


# att_ + 6..32 url-safe chars. Deliberately looser than a ULID so the minting
# side can evolve without a lockstep validator change; uniqueness is the CP's
# job, shape is ours.
ATTEMPT_ID_RE = re.compile(r"^att_[A-Za-z0-9_-]{6,32}$")

# secrets.token_hex(16) from the kernel's existing dispatch binding.
DISPATCH_ID_RE = re.compile(r"^[0-9a-f]{32}$")

PROFILE_ID_RE = re.compile(r"^[a-z][a-z0-9-]{2,63}$")

# The seven supervision sub-kinds (proposal 4.2), with a payload-key allowlist
# per kind. The allowlist is the privacy posture in code form (SP-SEC-037):
# an unknown key is refused rather than forwarded, so a leaky adapter fails
# fast in tests instead of shipping content to the control plane.
SUPERVISION_EVENT_KINDS = {
    "attempt/started": frozenset({"profile", "placement", "model_id"}),
    "attempt/status": frozenset({"status"}),
    "tool/call": frozenset({"tool", "summary", "duration_ms"}),
    "file/write": frozenset({"path", "size_bytes"}),
    "step/complete": frozenset({"label", "result", "digest"}),
    "budget/update": frozenset({"budget_kind", "consumed", "remaining"}),
    "runtime/error": frozenset({"error_kind", "diagnostic_level"}),
}

# Sized so a "summary" stays a summary. tool/call summaries and step labels
# are the two fields a lazy adapter would stuff raw output into.
MAX_EVENT_TEXT_LEN = 200

# Failure classification (SP-INT-017 design input). Versioned closed
# vocabulary; extend by appending and bumping FAILURE_CLASS_VERSION, never by
# ad-hoc strings in receipts.
FAILURE_CLASS_VERSION = 1
FAILURE_CLASSES = (
    "environment",
    "deterministic-check",
    "context-knowledge",
    "skill-rule",
    "workflow-structure",
    "agent-specialization",
    "model-policy",
    "cancelled-by-human",
    "budget-exhausted",
    "runtime-death",
    "unclassified",
)

# Typed evidence (pilot 2, #399; capability-profile-pilot.md 3.3). Every
# evidence item names the integrity discipline it lives under:
#   replayed -- verification_runner.py semantics, unchanged: a machine can
#               re-execute it and get the same answer. The discipline is the
#               executed-object shape that runner already demands: the command
#               that ran, and the exit code it returned.
#   attested -- structured agent-produced findings machines cannot replay
#               (challenge findings, review verdicts); bound to the producing
#               attempt identity from pilot 1 so an attestation belongs to
#               exactly one bounded execution.
#   judged   -- a human verdict; generalizes request_acceptance /
#               accept_story / reject_story. Its discipline fields are the
#               judged-verdict shape below.
EVIDENCE_CLASSES = ("replayed", "attested", "judged")

JUDGED_VERDICTS = ("accepted", "rejected")

# The shape check for judged.recorded_at. Deliberately a shape, not a parse:
# this module has no clock and takes no dependency on one; ordering and
# immutability once recorded are storage's and the kernel's jobs.
_ISO_TIMESTAMP_RE = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$"
)

# DoD check results (pilot 2, #399). `criteria_gap_declared` is the honest
# floor from capability-profile-pilot.md 3.3: a required check whose evidence
# shape cannot be evaluated declares the gap instead of passing silently, and
# the CP renders it as a visible gap (thin gates must look thin, the 13.3
# fix at the contract level).
DOD_CHECK_RESULTS = ("pass", "fail", "criteria_gap_declared")

#: The gap result by name, so producers and readers stop spelling the literal.
CRITERIA_GAP_DECLARED = "criteria_gap_declared"

_ENVELOPE_REQUIRED_STR = (
    "attempt_id",
    "dispatch_id",
    "project_id",
    "cycle_id",
    "manifest_hash",
    "story_id",
    "stage",
    "stage_profile",
    "role",
    "capability_profile",
    "adapter_profile_id",
    "runtime_family",
    "placement",
    "source_revision",
    "receipt_path",
    "expires_at",
    "fencing_token",
)

#: Fields that must be PRESENT and a string, and may be empty. Exactly one so
#: far, and it is a retirement in progress rather than a category.
#:
#: `SPD-194` retires the Workstream, so `advance_kernel._cycle_binding` writes
#: `workstream_id = ""` deliberately -- "the field stays in the envelope for one
#: release so a bridge built against the old contract still decodes; it is
#: written empty rather than dropped". This validator still demanded it
#: non-empty, so the two halves of one decision disagreed and
#: `_build_dispatch_envelope` failed EVERY governed SPQ dispatch with
#: `workstream_id: required non-empty string` -- the whole governed-runtime
#: path refused, with a message naming a concept that no longer exists.
#:
#: Presence is still checked, because dropping the key is the other half of the
#: retirement and is a separate release: an old bridge decoding this envelope
#: must find the field rather than a KeyError.
_ENVELOPE_PRESENT_STR = ("workstream_id",)


def _receipt_required_fields() -> List[str]:
    """The evidence contract's required receipt fields, or () if unreadable.

    Never raises and never guesses. An unreadable contract yields an empty
    list, which every reader is told to treat as "do not pre-judge" rather than
    as "nothing is required": the kernel validates the same document at advance
    either way, so the cost of an unreadable contract is earliness, not
    enforcement.
    """
    try:
        import evidence_contract  # noqa: PLC0415

        fields = evidence_contract.load_contract().get("receipt", {}).get(
            "required_fields", []
        )
    except Exception:  # noqa: BLE001
        return []
    return [str(f) for f in fields if isinstance(f, str) and f.strip()]


def build_envelope(
    *,
    attempt_id: str,
    dispatch_id: str,
    project_id: str,
    cycle_id: str,
    manifest_hash: str,
    workstream_id: str,
    story_id: str,
    stage: str,
    role: str,
    adapter_profile_id: str,
    runtime_family: str,
    placement: str,
    source_revision: str,
    receipt_path: str,
    expires_at: str,
    fencing_token: str,
    model_route: Optional[Dict[str, Any]] = None,
    materialization: Optional[Dict[str, Any]] = None,
    connector_refs: Optional[Dict[str, Any]] = None,
    config_refs: Optional[Dict[str, Any]] = None,
    workspace: Optional[Dict[str, Any]] = None,
    capability_ceiling: Optional[Sequence[str]] = None,
    network_allowlist: str = "project-default",
    budget: Optional[Dict[str, Any]] = None,
    required_evidence: Optional[Sequence[str]] = None,
    stage_profile: str = "",
    capability_profile: str = "",
) -> Dict[str, Any]:
    """Assemble a dispatch envelope. The kernel signs and persists the
    binding; this only shapes the object. stage_profile and capability_profile
    default from the role's dispatch-time projection so a caller cannot ship
    an envelope with the Platform overlay silently absent."""
    role_key = str(role or "").strip().lower()
    return {
        "schema_version": SCHEMA_VERSION,
        "kind": ENVELOPE_KIND,
        "attempt_id": str(attempt_id),
        "dispatch_id": str(dispatch_id),
        "project_id": str(project_id),
        "cycle_id": str(cycle_id),
        "manifest_hash": str(manifest_hash),
        "workstream_id": str(workstream_id),
        "story_id": str(story_id),
        "stage": str(stage),
        "stage_profile": str(
            stage_profile or DISPATCH_STAGE_PROFILE.get(role_key, "")
        ),
        "role": role_key,
        # THE FULL AGENT NAME, beside the abbrev rather than instead of it
        # (#626). Both vocabularies are correct and they did not meet: the
        # envelope's `role` is the abbrev by design, while a receipt's `role`
        # is the full name `evaluate_advance` compares against
        # `dispatch_profile()["role"]`. A bridge holding only an envelope could
        # therefore not fill in a required receipt field, and #627 had to leave
        # it absent rather than file `"qe"` and trade a missing-field refusal
        # for a `role_mismatch` one. Derived from `ROLE_NAMES`, which this
        # module already owns, so no host keeps a second copy of the table.
        "role_name": ROLE_NAMES.get(role_key, ""),
        # WHAT A RECEIPT OWES, minted here because this side owns the contract
        # (#592). A bridge told an attempt completed while the document it
        # filed omits required evidence has reported a status with nothing
        # behind it. Handing it the list lets it refuse at the moment it can
        # still say WHY, instead of the kernel refusing later with the runtime
        # long gone. Imported lazily: this module is the leaf every host
        # composes and `evidence_contract` loads files.
        "receipt_required_fields": _receipt_required_fields(),
        "capability_profile": str(
            capability_profile or DISPATCH_CAPABILITY_PROFILE.get(role_key, "")
        ),
        "adapter_profile_id": str(adapter_profile_id),
        "runtime_family": str(runtime_family),
        "placement": str(placement),
        "model_route": dict(model_route or {"requested": "policy-default"}),
        "source_revision": str(source_revision),
        "materialization": dict(materialization) if materialization else None,
        "connector_refs": dict(connector_refs) if connector_refs else None,
        "config_refs": dict(config_refs) if config_refs else None,
        "workspace": dict(workspace or {"mode": "existing-locked-worktree"}),
        "capability_ceiling": list(capability_ceiling or []),
        "network_allowlist": str(network_allowlist),
        "budget": dict(budget or {}),
        "receipt_path": str(receipt_path),
        "expires_at": str(expires_at),
        "fencing_token": str(fencing_token),
        "required_evidence": list(required_evidence or []),
    }


def _config_ref_problems(refs: Any) -> List[str]:
    """Why these `config_refs` may not be honoured. Empty = they may.

    `config_refs` is the one field naming where a runtime reads its
    CONFIGURATION from, which makes it the route by which a vendor's own
    conversation, memory, hook or session store becomes canonical V1 input.
    Nothing constrained it: the shipped fixture used `repo://` to show the
    intent and an envelope could name
    `file:///home/runner/.claude/projects/x/history.jsonl` and validate
    (proposal 11, "Vendor-state scan").

    Two accepted shapes, both of which the dispatch already pins:

      - a `repo://` reference, resolved inside the materialized tree at
        `source_revision`, so what it names is content the envelope committed
        to. The path is repo-relative: no root, no `..`, no drive or UNC
        prefix, because each of those leaves the tree.
      - an opaque identifier such as `preset_base`'s profile id, which names a
        thing the control plane resolves rather than a place on a disk.

    Anything else is refused, including any other scheme. That is deliberate:
    a new location scheme has to be added here on purpose, because "somewhere
    else on the runner's filesystem" is precisely the thing this refuses.
    """
    if refs is None:
        return []
    if not isinstance(refs, dict):
        return ["config_refs: must be an object"]
    problems: List[str] = []
    for name in sorted(refs):
        value = refs[name]
        if value is None:
            continue
        if not isinstance(value, str) or not value.strip():
            problems.append("config_refs.%s: must be a non-empty string" % name)
            continue
        ref = value.strip()
        if "://" in ref:
            if not ref.startswith(CONFIG_REF_SCHEME):
                problems.append(
                    "config_refs.%s: %r must be a %s reference into the "
                    "materialized tree. A runtime that reads its configuration "
                    "from anywhere the dispatch does not pin is how its own "
                    "conversation, memory or hook state becomes canonical"
                    % (name, ref, CONFIG_REF_SCHEME)
                )
                continue
            path = ref[len(CONFIG_REF_SCHEME):]
        else:
            # An opaque identifier. It names something the control plane
            # resolves, so it must not look like a location at all.
            if any(ch in ref for ch in ("/", "\\")) or ref.startswith("~"):
                problems.append(
                    "config_refs.%s: %r is neither a %s reference nor an opaque "
                    "identifier. A bare path is read on the runner's own "
                    "filesystem, which the dispatch does not pin"
                    % (name, ref, CONFIG_REF_SCHEME)
                )
            continue
        if not path or path.startswith("/") or path.startswith("~"):
            problems.append(
                "config_refs.%s: %r must name a repository-relative path"
                % (name, ref)
            )
            continue
        if "\\" in path or re.match(r"^[A-Za-z]:", path):
            problems.append(
                "config_refs.%s: %r must name a repository-relative POSIX path"
                % (name, ref)
            )
            continue
        if any(segment == ".." for segment in path.split("/")):
            problems.append(
                "config_refs.%s: %r escapes the materialized tree" % (name, ref)
            )
    return problems


def config_ref_problems(refs: Any) -> List[str]:
    """Public name for the `config_refs` rule, for callers that DERIVE the map.

    `runtime_materialization` builds `config_refs` from a project's declared
    `config_sources`, and it validates the result here so the refusal names the
    field an operator can edit rather than the field the kernel derived. It is
    the same rule `validate_envelope` applies, deliberately reused rather than
    restated: a second copy is how a source the envelope would refuse comes to
    pass the check that precedes it.
    """
    return _config_ref_problems(refs)


def config_ref_containment_problem(checkout: str, ref: Any) -> str:
    """Why the resolved config file is not inside the checkout, or "".

    THE LEXICAL RULE IS NOT CONTAINMENT. `_config_ref_problems` establishes
    that an envelope may not NAME a path outside the materialized tree, and
    that is where it stops: `repo://.synaptory.yaml` is a valid name, and after
    checkout a materialized revision may contain
    `.synaptory.yaml -> /home/runner/.claude/.../state`, or an intermediate
    directory symlink, and an ordinary open follows it. The signed
    `source_revision` pins the symlink TEXT, not the target's content, so the
    envelope stays valid while the reader takes host and vendor state as
    governance input (#396, proposal 11 "Vendor-state scan").

    So every component is resolved, and a SYMLINK COMPONENT IS REFUSED
    OUTRIGHT, including one whose target is inside the tree. Refusing only the
    escaping ones would mean deciding containment from a target that can change
    between the check and the open; refusing the component removes the question
    and the race with it. A repository that needs the same file in two places
    can commit it in both.
    """
    problems = _config_ref_problems({"synaptory_yaml": ref})
    if problems:
        return problems[0]
    rel = str(ref or "").strip()
    if rel.startswith(CONFIG_REF_SCHEME):
        rel = rel[len(CONFIG_REF_SCHEME):]
    if not rel:
        rel = ".synaptory.yaml"
    try:
        root = os.path.realpath(checkout)
    except OSError as exc:  # pragma: no cover - unreadable checkout root
        return "the checkout could not be resolved: %s" % exc
    if not os.path.isdir(root):
        return "the checkout %r is not a directory" % checkout
    current = root
    parts = [p for p in rel.split("/") if p]
    for index, part in enumerate(parts):
        current = os.path.join(current, part)
        if os.path.islink(current):
            return (
                "config_refs.synaptory_yaml: %r is a symlink inside the "
                "materialized tree, and a signed revision pins its TEXT rather "
                "than what it points at. A runtime that read through it would "
                "take whatever is on the runner's filesystem as governance"
                % "/".join(parts[: index + 1])
            )
        if not os.path.exists(current):
            return (
                "config_refs.synaptory_yaml: the checked-out tree has no %r"
                % rel
            )
    if not os.path.isfile(current):
        return "config_refs.synaptory_yaml: %r is not a file" % rel
    resolved = os.path.realpath(current)
    if resolved != root and not resolved.startswith(root + os.sep):
        # Unreachable once every component is checked, and kept because
        # containment is the property, not the walk that establishes it.
        return (
            "config_refs.synaptory_yaml: %r resolves to %r, outside the "
            "materialized tree" % (rel, resolved)
        )
    return ""


def validate_envelope(env: Any) -> List[str]:
    """Every reason this is not a well-formed dispatch envelope. Empty = pass.

    Secrets are refused structurally: connector_refs values must be cred://
    references, never inline material, because the envelope is an authority
    ceiling that crosses process boundaries and gets logged.
    """
    problems: List[str] = []
    if not isinstance(env, dict):
        return ["envelope: not an object"]
    if env.get("schema_version") != SCHEMA_VERSION:
        problems.append(
            "schema_version: expected %d, got %r"
            % (SCHEMA_VERSION, env.get("schema_version"))
        )
    if env.get("kind") != ENVELOPE_KIND:
        problems.append("kind: expected %r, got %r" % (ENVELOPE_KIND, env.get("kind")))
    for field in _ENVELOPE_REQUIRED_STR:
        value = env.get(field)
        if not isinstance(value, str) or not value.strip():
            problems.append("%s: required non-empty string" % field)
    for field in _ENVELOPE_PRESENT_STR:
        if not isinstance(env.get(field), str):
            problems.append(
                "%s: required string, and may be empty while the field is "
                "retained for decode compatibility" % field
            )
    attempt_id = env.get("attempt_id")
    if isinstance(attempt_id, str) and attempt_id and not ATTEMPT_ID_RE.match(attempt_id):
        problems.append("attempt_id: %r does not match %s" % (attempt_id, ATTEMPT_ID_RE.pattern))
    dispatch_id = env.get("dispatch_id")
    if isinstance(dispatch_id, str) and dispatch_id and not DISPATCH_ID_RE.match(dispatch_id):
        problems.append("dispatch_id: not a 32-char lowercase hex token")
    profile_id = env.get("adapter_profile_id")
    if isinstance(profile_id, str) and profile_id and not PROFILE_ID_RE.match(profile_id):
        problems.append("adapter_profile_id: %r is not a valid profile id" % profile_id)
    placement = env.get("placement")
    if placement not in PLACEMENTS:
        problems.append("placement: %r not in %r" % (placement, PLACEMENTS))
    if env.get("runtime_family") not in RUNTIME_FAMILIES:
        problems.append(
            "runtime_family: %r not in %r" % (env.get("runtime_family"), RUNTIME_FAMILIES)
        )
    # `role` is the receipt ABBREV, not the full agent name. Both spellings
    # existed in the draft (the proposal's example envelope said
    # "quality-engineer" while the projection tables are keyed by "qe"), and
    # nothing constrained the field, so an envelope could carry either and
    # validate. The abbrev wins because it is what the kernel already binds
    # (`mcp_active_dispatches[abbrev]`) and what the canonical receipt
    # filename uses; the full name lives on in the receipt's `agent` field.
    if env.get("role") not in DISPATCH_CAPABILITY_PROFILE:
        problems.append(
            "role: %r is not a dispatch role abbrev (expected one of %r; the "
            "full agent name belongs in the receipt's `agent` field)"
            % (env.get("role"), sorted(DISPATCH_CAPABILITY_PROFILE))
        )
    if env.get("stage_profile") not in STAGE_PROFILES:
        problems.append(
            "stage_profile: %r not in %r" % (env.get("stage_profile"), STAGE_PROFILES)
        )
    if env.get("capability_profile") not in CAPABILITY_PROFILES:
        problems.append(
            "capability_profile: %r not in %r"
            % (env.get("capability_profile"), CAPABILITY_PROFILES)
        )
    if env.get(ACCOUNTABLE_ROLE) is not None:
        problems.extend(_accountable_role_problems(env.get(ACCOUNTABLE_ROLE)))
    # Managed placement must be independently materializable: the runner has
    # no host environment to fall back to (proposal 4.5, 6.4). Local
    # placements may omit both blocks and use the host's own checkout.
    if placement == "managed-laptop":
        receipt_path = str(env.get("receipt_path") or "").replace("\\", "/")
        clean_receipt = posixpath.normpath(receipt_path)
        if (
            posixpath.isabs(clean_receipt)
            or clean_receipt == ".."
            or clean_receipt.startswith("../")
        ):
            problems.append(
                "receipt_path: managed placement requires a relative path inside the disposable workspace"
            )
        mat = env.get("materialization")
        if not isinstance(mat, dict):
            problems.append("materialization: required for managed placement")
        else:
            for field in ("repo_url", "ref", "revision"):
                if not str(mat.get(field) or "").strip():
                    problems.append("materialization.%s: required non-empty" % field)
            if (
                str(mat.get("revision") or "").strip()
                and str(mat.get("revision")) != str(env.get("source_revision"))
            ):
                problems.append(
                    "materialization.revision: must equal source_revision for managed placement"
                )
        managed_refs = env.get("connector_refs")
        if not isinstance(managed_refs, dict) or not managed_refs:
            problems.append(
                "connector_refs: required non-empty project connector mapping for managed placement"
            )
        elif managed_refs.get("llm") is not None:
            problems.append(
                "connector_refs.llm: must be absent or null; managed Claude subscription authentication belongs to the runner, not an attempt token"
            )
        workspace = env.get("workspace")
        if not isinstance(workspace, dict) or workspace.get("mode") != "clean-isolated":
            problems.append(
                "workspace.mode: managed placement requires clean-isolated"
            )
        if not env.get("capability_ceiling"):
            problems.append(
                "capability_ceiling: managed placement requires a non-empty authority ceiling"
            )
    refs = env.get("connector_refs")
    if isinstance(refs, dict):
        for name, ref in refs.items():
            if ref is None:
                continue
            if not isinstance(ref, str) or not ref.startswith("cred://"):
                problems.append(
                    "connector_refs.%s: must be a cred:// reference, never inline material"
                    % name
                )
    problems.extend(_config_ref_problems(env.get("config_refs")))
    ceiling = env.get("capability_ceiling")
    if not isinstance(ceiling, list) or not all(isinstance(c, str) for c in ceiling or []):
        problems.append("capability_ceiling: must be a list of strings")
    budget = env.get("budget")
    if not isinstance(budget, dict):
        problems.append("budget: must be an object")
    return problems


#: The immutable authority body: exactly the fields the Control Plane signs
#: (proposal 4.4.1). Every field that grants, narrows, or targets authority is
#: here. `fencing_token` is NOT, on purpose: it is lease-issued, re-issued on
#: every claim, and rewritten in the worker's memory, so signing it would
#: either break the signature on the normal path or freeze a generation that
#: has to move. It is bound by indirection instead, through `attempt_id` and
#: the CP claim response, which is the only place a current generation comes
#: from. `signature` itself is excluded for the obvious reason.
ENVELOPE_SIGNED_FIELDS: Tuple[str, ...] = (
    "adapter_profile_id",
    "attempt_id",
    "budget",
    "capability_ceiling",
    "capability_profile",
    "config_refs",
    "connector_refs",
    "cycle_id",
    "dispatch_id",
    "expires_at",
    "kind",
    "manifest_hash",
    "materialization",
    "model_route",
    "network_allowlist",
    "placement",
    "project_id",
    "receipt_path",
    "receipt_required_fields",
    "required_evidence",
    "role",
    "role_name",
    "runtime_family",
    "schema_version",
    "source_revision",
    "stage",
    "stage_profile",
    "story_id",
    "workspace",
    "workstream_id",
)

SIGNATURE_ALG = "ed25519"


def envelope_signing_payload(env: Dict[str, Any]) -> bytes:
    """The exact bytes signed and verified: canonical JSON over the authority
    body, sorted keys, no insignificant whitespace.

    Same canonicalization as the config-version signer
    (`api/synaptory_api/routers/config.py::_canonical`), so there is one
    convention to get right rather than two. A missing field is signed as
    absent rather than as null, so an envelope cannot gain a field after
    signing without invalidating the signature.
    """
    import json

    body = {k: env[k] for k in ENVELOPE_SIGNED_FIELDS if k in env}
    return json.dumps(body, sort_keys=True, separators=(",", ":")).encode("utf-8")


def envelope_signature_problems(env: Any) -> List[str]:
    """Every reason this envelope's `signature` block is not well formed.

    Shape only. Whether the signature VERIFIES needs a public key and lives in
    `verify_envelope_signature`; this is the part every host can check without
    reaching the control plane.
    """
    problems: List[str] = []
    if not isinstance(env, dict):
        return ["envelope: not an object"]
    sig = env.get("signature")
    if not isinstance(sig, dict):
        return ["signature: required object"]
    if sig.get("alg") != SIGNATURE_ALG:
        problems.append(
            "signature.alg: expected %r, got %r" % (SIGNATURE_ALG, sig.get("alg"))
        )
    for field in ("key_id", "value"):
        if not isinstance(sig.get(field), str) or not str(sig.get(field)).strip():
            problems.append("signature.%s: required non-empty string" % field)
    return problems


def verify_envelope_signature(env: Any, public_key_pem: bytes) -> List[str]:
    """Every reason this envelope's signature does not verify. Empty = verified.

    Fails CLOSED on a missing `cryptography` module rather than reporting a
    pass: "we could not check" and "we checked and it is fine" must never
    produce the same answer at an authority boundary.
    """
    problems = envelope_signature_problems(env)
    if problems:
        return problems
    import base64

    try:
        from cryptography.hazmat.primitives.serialization import load_pem_public_key
        from cryptography.exceptions import InvalidSignature
    except Exception as exc:  # noqa: BLE001
        return ["signature: cannot verify (%s)" % exc]
    try:
        key = load_pem_public_key(public_key_pem)
    except Exception as exc:  # noqa: BLE001
        return ["signature: unusable public key (%s)" % exc]
    raw = str(env["signature"]["value"])
    try:
        blob = base64.urlsafe_b64decode(raw + "=" * (-len(raw) % 4))
    except Exception:  # noqa: BLE001
        return ["signature.value: not base64url"]
    try:
        key.verify(blob, envelope_signing_payload(env))
    except InvalidSignature:
        return ["signature: does not verify against the control-plane key"]
    except Exception as exc:  # noqa: BLE001
        return ["signature: verification failed (%s)" % exc]
    return []


def sign_envelope(env: Dict[str, Any], signer: Any, key_id: str) -> Dict[str, Any]:
    """Return `env` with a `signature` block over its authority body.

    `signer` is anything with `.sign(bytes) -> bytes`, which is the control
    plane's existing `Signer` protocol (file-backed in dev, Key Vault in
    prod), so envelopes carry no key hierarchy of their own.
    """
    import base64

    blob = signer.sign(envelope_signing_payload(env))
    signed = dict(env)
    signed["signature"] = {
        "alg": SIGNATURE_ALG,
        "key_id": str(key_id),
        "value": base64.urlsafe_b64encode(blob).decode("ascii").rstrip("="),
    }
    return signed


def validate_supervision_event(event: Any) -> List[str]:
    """Every reason this is not a well-formed, privacy-safe supervision event.

    The payload allowlist is deliberately closed: content the table in
    proposal 3.5 says never leaves the runtime has no field to travel in.
    """
    problems: List[str] = []
    if not isinstance(event, dict):
        return ["event: not an object"]
    seq = event.get("seq")
    if not isinstance(seq, int) or isinstance(seq, bool) or seq < 1:
        problems.append("seq: required integer >= 1")
    if not str(event.get("ts") or "").strip():
        problems.append("ts: required non-empty timestamp string")
    attempt_id = event.get("attempt_id")
    if not isinstance(attempt_id, str) or not ATTEMPT_ID_RE.match(attempt_id or ""):
        problems.append("attempt_id: required, matching %s" % ATTEMPT_ID_RE.pattern)
    if event.get("privacy_safe") is not True:
        problems.append("privacy_safe: must be literal true")
    kind = event.get("kind")
    allowed = SUPERVISION_EVENT_KINDS.get(kind or "")
    if allowed is None:
        problems.append(
            "kind: %r not in %r" % (kind, sorted(SUPERVISION_EVENT_KINDS))
        )
        return problems
    payload = event.get("payload")
    if not isinstance(payload, dict):
        problems.append("payload: required object")
        return problems
    extra = set(payload) - allowed
    if extra:
        problems.append(
            "payload: keys %r not allowed for kind %r (allowlist: %r)"
            % (sorted(extra), kind, sorted(allowed))
        )
    for key, value in payload.items():
        if isinstance(value, str) and len(value) > MAX_EVENT_TEXT_LEN:
            problems.append(
                "payload.%s: %d chars exceeds the %d-char summary cap"
                % (key, len(value), MAX_EVENT_TEXT_LEN)
            )
        if isinstance(value, (dict, list)):
            problems.append("payload.%s: nested structures are not allowed" % key)
    return problems


def validate_profile(record: Any) -> List[str]:
    """Every reason this is not a well-formed adapter-profile record.

    A profile is the immutable certified combination of adapter, runtime,
    placement, and capabilities (proposal 3.1). capability_profiles is the
    Platform overlay: which of the four profiles this runtime may serve, the
    selector's policy key (r4 amendment)."""
    problems: List[str] = []
    if not isinstance(record, dict):
        return ["profile: not an object"]
    profile_id = record.get("profile_id")
    if not isinstance(profile_id, str) or not PROFILE_ID_RE.match(profile_id or ""):
        problems.append("profile_id: required, matching %s" % PROFILE_ID_RE.pattern)
    if record.get("runtime_family") not in RUNTIME_FAMILIES:
        problems.append(
            "runtime_family: %r not in %r"
            % (record.get("runtime_family"), RUNTIME_FAMILIES)
        )
    if record.get("placement") not in PLACEMENTS:
        problems.append(
            "placement: %r not in %r" % (record.get("placement"), PLACEMENTS)
        )
    if not str(record.get("pinned_version") or "").strip():
        problems.append("pinned_version: required non-empty string")
    served = record.get("capability_profiles")
    if (
        not isinstance(served, list)
        or not served
        or not set(served) <= set(CAPABILITY_PROFILES)
    ):
        problems.append(
            "capability_profiles: required non-empty subset of %r"
            % (CAPABILITY_PROFILES,)
        )
    caps = record.get("capabilities")
    if not isinstance(caps, list) or not all(isinstance(c, str) for c in caps or []):
        problems.append("capabilities: must be a list of strings")
    return problems


def validate_receipt_attempt_binding(receipt: Any) -> List[str]:
    """The attempt-identity fields a pilot receipt payload must carry
    (proposal 4.4: identity lives in the payload, never the filename).
    Enforcement at advance is the kernel's job (#342/#344); this names the
    shape so hosts and fixtures agree on it."""
    problems: List[str] = []
    if not isinstance(receipt, dict):
        return ["receipt: not an object"]
    attempt_id = receipt.get("attempt_id")
    if not isinstance(attempt_id, str) or not ATTEMPT_ID_RE.match(attempt_id or ""):
        problems.append("attempt_id: required, matching %s" % ATTEMPT_ID_RE.pattern)
    dispatch_id = receipt.get("dispatch_id")
    if not isinstance(dispatch_id, str) or not DISPATCH_ID_RE.match(dispatch_id or ""):
        problems.append("dispatch_id: required 32-char lowercase hex token")
    profile_id = receipt.get("adapter_profile_id")
    if not isinstance(profile_id, str) or not PROFILE_ID_RE.match(profile_id or ""):
        problems.append(
            "adapter_profile_id: required, matching %s" % PROFILE_ID_RE.pattern
        )
    if receipt.get("placement") not in PLACEMENTS:
        problems.append(
            "placement: required runtime placement in %r" % (PLACEMENTS,)
        )
    source_revision = receipt.get("source_revision")
    if not isinstance(source_revision, str) or not source_revision.strip():
        problems.append("source_revision: required non-empty string")
    # #592. The lease generation, named here for the same reason every field
    # above it is: this shape describes a GOVERNED receipt, one the bridge
    # produced under a kernel-minted envelope, and `stampReceiptIdentity`
    # projects the generation onto it (#607). Leaving it optional while
    # requiring `attempt_id`, `dispatch_id`, `adapter_profile_id`, `placement`
    # and `source_revision` said the runner must prove which attempt and which
    # profile it ran as, but not which GENERATION of the lease it still holds,
    # which is the only one of them a superseded runner would get wrong.
    #
    # No format is asserted. The kernel mints 32 hex characters locally, while
    # a coordinator-issued generation is whatever the control plane issues, and
    # a regex here would refuse a valid one to look strict.
    fencing_token = receipt.get("fencing_token")
    if not isinstance(fencing_token, str) or not fencing_token.strip():
        problems.append(
            "fencing_token: required non-empty string; a governed receipt "
            "carries the lease generation its runner holds, and a runner that "
            "presents none cannot be shown to be the current one"
        )
    failure_class = receipt.get("failure_class")
    if failure_class is not None:
        if failure_class not in FAILURE_CLASSES:
            problems.append(
                "failure_class: %r not in the v%d vocabulary %r"
                % (failure_class, FAILURE_CLASS_VERSION, FAILURE_CLASSES)
            )
        elif failure_class == UNCLASSIFIED_FAILURE:
            # SP-INT-017, the half that was declared and not enforced. The
            # coordination route already refuses an unclassified close, so a
            # RECEIPT carrying it describes a close that could not have
            # happened, and it is the receipt that outlives the attempt. A
            # runner that genuinely does not know narrows to `runtime-death`,
            # which is a cause; `unclassified` is the absence of one.
            problems.append(
                "failure_class: %r is transient only: it may be recorded locally "
                "while a runner is still deciding, but it may not CLOSE an attempt, and a "
                "receipt is the record of a closed one (SP-INT-017). Name the "
                "cause, or `runtime-death` when the runtime died without one"
                % UNCLASSIFIED_FAILURE
            )
    if receipt.get(ACCOUNTABLE_ROLE) is not None:
        problems.extend(_accountable_role_problems(receipt.get(ACCOUNTABLE_ROLE)))
    return problems


def validate_judged_verdict(obj: Any) -> List[str]:
    """Every reason this is not a well-formed judged verdict. Empty = pass.

    The judged discipline (capability-profile-pilot.md 3.3, SP-WRK-014's
    human analogue): a named principal, the verdict bound to the exact
    candidate identity (a receipt digest or selected_sha), a definite
    recording instant, and independence from the producing principal
    RECORDED, never assumed. `independent_of_producer: false` is a valid
    value: non-independence is recorded rather than refused, and any refusal
    rule is a later policy decision, not vocabulary. Immutability once
    recorded is storage's obligation; this names the shape a stored verdict
    must have."""
    problems: List[str] = []
    if not isinstance(obj, dict):
        return ["judged verdict: not an object"]
    principal = obj.get("principal")
    if not isinstance(principal, str) or not principal.strip():
        problems.append(
            "principal: required non-empty string naming the human who judged"
        )
    candidate_digest = obj.get("candidate_digest")
    if not isinstance(candidate_digest, str) or not candidate_digest.strip():
        problems.append(
            "candidate_digest: required non-empty string binding the verdict "
            "to the exact candidate (a receipt digest or selected_sha)"
        )
    verdict = obj.get("verdict")
    if verdict not in JUDGED_VERDICTS:
        problems.append("verdict: %r not in %r" % (verdict, JUDGED_VERDICTS))
    recorded_at = obj.get("recorded_at")
    if not isinstance(recorded_at, str) or not _ISO_TIMESTAMP_RE.match(recorded_at):
        problems.append(
            "recorded_at: required ISO-8601 timestamp "
            "(e.g. 2026-09-02T10:15:00Z), got %r" % (recorded_at,)
        )
    independent = obj.get("independent_of_producer")
    if not isinstance(independent, bool):
        problems.append(
            "independent_of_producer: required boolean; independence from the "
            "producing principal is recorded, never assumed (false is valid "
            "and is recorded, not refused)"
        )
    return problems


def validate_evidence_item(item: Any) -> List[str]:
    """Every reason this is not a well-formed typed evidence item.

    The class names the integrity discipline, and the discipline names the
    fields:

    * `replayed` must name the command that ran and the exit code it
      returned. This is the executed-object shape `verification_runner.py`
      already demands and `story_pipeline._evaluate_check` already keys on
      ("plain-string commands are replay instructions, not evidence"), and
      the runner's semantics are unchanged: the item says WHAT a machine can
      re-execute, the runner decides whether it reproduces.
    * `attested` must carry the producing attempt identity so the
      attestation is bound to one bounded execution.
    * `judged` must satisfy the full judged-verdict discipline.

    `check_id` is optional and validated when present: it links the item to
    the DoD check it is evidence FOR, which is what lets a reader credit
    depth to that check and to no other. An item that names no check backs
    no check.

    #403 correction to #399. As landed, `replayed` required nothing beyond
    the class, so `{"evidence_class": "replayed"}` was a well-formed replayed
    item -- a bare token asserting that something reproduced, naming nothing
    that could be re-run. That is the same defect #432 fixed on the read side
    ("a bare {"evidence_class": "replayed"} credited every check that named
    replayed"), and refusing it belongs here rather than in each reader.
    """
    problems: List[str] = []
    if not isinstance(item, dict):
        return ["evidence: not an object"]
    evidence_class = item.get("evidence_class")
    if evidence_class not in EVIDENCE_CLASSES:
        problems.append(
            "evidence_class: %r not in %r; an untyped evidence item has no "
            "integrity discipline to check it against"
            % (evidence_class, EVIDENCE_CLASSES)
        )
        return problems
    check_id = item.get("check_id")
    if check_id is not None and (
        not isinstance(check_id, str) or not check_id.strip()
    ):
        problems.append(
            "check_id: must be a non-empty string naming the DoD check this "
            "item is evidence for, when present"
        )
    if evidence_class == "replayed":
        command = item.get("command")
        if not isinstance(command, str) or not command.strip():
            problems.append(
                "command: a replayed item must name the command a machine can "
                "re-execute; a class token with no command asserts a replay "
                "of nothing"
            )
        exit_code = item.get("exit_code")
        if not isinstance(exit_code, int) or isinstance(exit_code, bool):
            problems.append(
                "exit_code: a replayed item must record the integer exit code "
                "the command actually returned (a declared command with no "
                "recorded exit code was never executed)"
            )
    if evidence_class == "attested":
        # SHAPE ONLY, and saying so here is the point (#493). A regular
        # expression refuses a MALFORMED attempt id and never an UNAUTHORIZED
        # one, so this line cannot tell a grade produced by the dispatched
        # execution from a grade naming an execution that never ran. The
        # authorization comparison needs the story's dispatch record, which
        # this module has no access to by design (#399 kept it the dependency
        # leaf and mirrored ROLE_NAMES rather than importing the kernel), so
        # it lives in `advance_kernel.evaluate_advance` and reads its claims
        # through `attested_attempt_claims` below.
        attempt_id = item.get("attempt_id")
        if not isinstance(attempt_id, str) or not ATTEMPT_ID_RE.match(attempt_id or ""):
            problems.append(
                "attempt_id: an attested item must carry the producing "
                "attempt identity (matching %s) so the attestation is bound "
                "to one bounded execution" % ATTEMPT_ID_RE.pattern
            )
    if evidence_class == "judged":
        problems.extend(validate_judged_verdict(item))
    return problems


def attested_attempt_claims(receipt: Any) -> List[Tuple[int, str]]:
    """Every `(index, attempt_id)` an `attested` item on this receipt CLAIMS.

    A reader, not a judge. It reports which executions a receipt attributes
    its attestations to and says nothing about whether any of them happened:
    `attested` is the one class whose whole discipline is that identity
    (`replayed` earns its credit by re-execution and `judged` by a derived
    candidate digest plus a named principal), and until #493 the identity was
    matched against `ATTEMPT_ID_RE` and compared to nothing. Deciding whether
    a claim was authorized needs project state, so the kernel does that with
    this function's output.

    Items whose attempt id is not well formed are skipped rather than
    reported: `validate_evidence_item` already refuses them and
    `receipt_validator._validate_typed_evidence` raises that to a
    `receipt_invalid` refusal, which the kernel reaches BEFORE the binding
    check. A malformed claim is therefore already dead, and repeating it here
    would only produce a second message for one defect.
    """
    if not isinstance(receipt, dict):
        return []
    evidence = receipt.get("evidence")
    if not isinstance(evidence, list):
        return []
    claims: List[Tuple[int, str]] = []
    for index, item in enumerate(evidence):
        if not isinstance(item, dict) or item.get("evidence_class") != "attested":
            continue
        attempt_id = item.get("attempt_id")
        if isinstance(attempt_id, str) and ATTEMPT_ID_RE.match(attempt_id):
            claims.append((index, attempt_id))
    return claims


def backed_evidence_class(item: Any) -> Optional[str]:
    """The class this evidence item actually SUPPORTS, or None.

    An item DECLARES a class; this says whether it carries the discipline
    that class names. An item that does not is UNBACKED and must be credited
    at no class at all -- never at the one it claimed. That is the #432 rule,
    and this is the function that owns it: `api`'s
    `_evidence_item_is_well_formed` mirrors this decision for the read side,
    and where the two disagree this one is right and that one is the bug.

    Returning None rather than raising is deliberate. Every caller is
    deciding how much credit to give a claim, not whether to accept a
    document, so "no class" is the useful answer and the fail-closed one.
    Use `validate_evidence_item` when the caller needs to tell a writer WHY.
    """
    if validate_evidence_item(item):
        return None
    return str(item.get("evidence_class"))


def evidence_class_by_check(items: Any) -> Dict[str, Tuple[str, ...]]:
    """Per CHECK id, the classes the given evidence items can actually back.

    Two rules, both #432's: an item backs only the check it names in
    `check_id` (an item that names none backs nothing, so a receipt cannot
    have one well-shaped item credit five checks), and an item backs only the
    class whose discipline it meets. Keys are normalized to the pipeline's
    underscore spelling so `coverage-no-decrease` and `coverage_no_decrease`
    are the same check.
    """
    out: Dict[str, set] = {}
    if not isinstance(items, list):
        return {}
    for item in items:
        supported = backed_evidence_class(item)
        if supported is None:
            continue
        check_id = item.get("check_id")
        if not isinstance(check_id, str) or not check_id.strip():
            continue
        key = check_id.strip().lower().replace("-", "_")
        out.setdefault(key, set()).add(supported)
    return {k: tuple(sorted(v)) for k, v in out.items()}


def validate_dod_check_result(obj: Any) -> List[str]:
    """Every reason this is not a well-formed DoD check result.

    `criteria_gap_declared` REQUIRES a non-empty detail naming the missing
    evidence shape: the whole point of the result is that the gap is visible
    and actionable on the gate, so a gap with no description would be a
    silent pass wearing a different label."""
    problems: List[str] = []
    if not isinstance(obj, dict):
        return ["dod check result: not an object"]
    check_id = obj.get("check_id")
    if not isinstance(check_id, str) or not check_id.strip():
        problems.append("check_id: required non-empty string")
    result = obj.get("result")
    if result not in DOD_CHECK_RESULTS:
        problems.append("result: %r not in %r" % (result, DOD_CHECK_RESULTS))
    detail = obj.get("detail")
    if detail is not None and not isinstance(detail, str):
        problems.append("detail: must be a string when present")
    if result == "criteria_gap_declared" and (
        not isinstance(detail, str) or not detail.strip()
    ):
        problems.append(
            "detail: criteria_gap_declared requires a non-empty detail "
            "naming the missing evidence shape, so the gap renders as "
            "actionable on the gate instead of as a silent pass"
        )
    return problems
