#!/usr/bin/env python3
# GENERATED by plugin-cursor/scripts/compose.sh — edit core/ or plugin-claude/ then re-compose
# Copyright 2024-2026 H3Tech Inc. All rights reserved. PROPRIETARY.
"""Session manager — v2.5-shaped interface over a pluggable backend.

In v2.1.16 this has one backend (`LocalBackend`) that reads the long-lived
access token, verifies its Ed25519 signature, mints a session token, decrypts
the `.enc` skill tree, and caches a `SessionRecord` on disk.

In v2.1.18 the `ControlPlaneBackend` will be wired, and `SessionManager`
selects between them based on the stamped URL in `hooks/lib/cp-url.local`
(or `hooks/lib/cp-url`), with unreachable CP → fall back to local per user
directive. Runtime SYNAPTORY_CONTROL_PLANE_URL is ignored.

In v2.5 the `LocalBackend` is deleted; the dispatcher always calls the Go
CLI (`synaptory login --if-needed`) which populates the OS keychain with a
byte-identical `SessionRecord` JSON. Every downstream caller stays on this
module's public surface, so the merge is a module swap, not a rewrite.

Public surface (stable across all versions):
    SessionManager().login(project=...) -> SessionRecord
    SessionManager().whoami(project=...) -> SessionRecord | None
    SessionManager().logout(project=...) -> bool
    SessionManager().activate(plugin_root, project=...) -> dict
        # Full SessionStart flow: login + decrypt tree + stamp watermark +
        # write /tmp/.synaptory-session-root marker. Returns the decrypt
        # summary dict for the hook's status message.
    SessionManager().fetch_skill(name) -> str
        # Used by /synaptory skills sync and by any per-skill fallback.

CLI (for hook scripts):
    session_manager.py login [--project <slug>]
    session_manager.py whoami [--project <slug>]
    session_manager.py logout [--project <slug>]
    session_manager.py activate <plugin_root> [--project <slug>]
    session_manager.py fetch-skill <name>
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import access_token_client as atc  # noqa: E402
import session_store  # noqa: E402
from session_store import SessionRecord  # noqa: E402


def _host_env():
    """Lazy import so a partial install cannot break module load."""
    import host_env

    return host_env



LOCAL_URL = "local"
DEFAULT_PROJECT = "default"


class SessionError(Exception):
    """Raised on any activation failure. Message is user-facing."""


# ── Backend protocol ─────────────────────────────────────────────────────────

class Backend:
    """Protocol — duck-typed. Both local and control-plane implementations
    honor this surface."""

    def name(self) -> str: ...
    def login(self, project_id: str) -> SessionRecord: ...
    def fetch_skill_body(self, skill_name: str) -> str: ...


# ── Local backend (interim, v2.1.16+) ────────────────────────────────────────

class LocalBackend(Backend):
    """Reads the long-lived access token, verifies Ed25519, mints a local
    session token, caches a SessionRecord, returns it. No network."""

    def __init__(self, access_token: str):
        self._token = access_token

    def name(self) -> str:
        return "local"

    def login(self, project_id: str) -> SessionRecord:
        try:
            access_payload = atc.validate_access_token(self._token)
        except ValueError as e:
            raise SessionError(str(e))

        session_token, session_payload = atc.mint_local_session_token(
            self._token, project_id=project_id
        )

        now = datetime.now(timezone.utc)
        exp = datetime.fromtimestamp(session_payload["exp"], tz=timezone.utc)
        record = SessionRecord(
            control_plane_url=LOCAL_URL,
            upn=access_payload["upn"],
            project_id=project_id,
            role=access_payload.get("role", "member"),
            session_token=session_token,
            refresh_token="",  # local mode has no refresh — long-lived access token is the refresh
            expires_at=exp,
            issued_at=now,
        )
        session_store.save(record)
        return record

    def fetch_skill_body(self, skill_name: str) -> str:
        plugin_root = _host_env().plugin_root(
            os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        )

        # Skills live under either skills/<name>/SKILL.md or
        # agents/<name>/{SKILL.md,agent.md}. Return the first hit.
        candidates = [
            ("skills", skill_name, "SKILL.md"),
            ("agents", skill_name, "SKILL.md"),
            ("agents", skill_name, "agent.md"),
        ]

        # Prefer already-decrypted session copy over re-decryption.
        sdir = atc.get_session_dir()
        if sdir:
            for parts in candidates:
                p = os.path.join(sdir, *parts)
                if os.path.exists(p):
                    with open(p) as f:
                        return f.read()

        # On-demand single-file decrypt.
        for parts in candidates:
            enc = os.path.join(plugin_root, *parts) + ".enc"
            if os.path.exists(enc):
                master_pw = atc.derive_access_token_password(self._token)
                watermark = atc.get_access_token_watermark(self._token)
                import tempfile

                tmp = tempfile.NamedTemporaryFile(
                    "r+", delete=False, prefix="synaptory-skill-", encoding="utf-8"
                )
                try:
                    if not atc.decrypt_file(master_pw, enc, tmp.name, watermark):
                        raise SessionError(f"decrypt failed for {enc}")
                    with open(tmp.name) as f:
                        return f.read()
                finally:
                    try:
                        os.unlink(tmp.name)
                    except OSError:
                        pass

        # Plaintext dev mode — source tree.
        for parts in candidates:
            plain = os.path.join(plugin_root, *parts)
            if os.path.exists(plain):
                with open(plain) as f:
                    return f.read()

        raise SessionError(
            f"Skill {skill_name!r} not found under skills/ or agents/ in {plugin_root}"
        )


# ── Control-plane backend (wired in v2.1.18, body filled in by v2.5 merge) ──

def _cli_url_is_local(url: str) -> bool:
    u = (url or "").lower()
    return "localhost" in u or "127." in u or "::1" in u


def _resolve_cli_binary(url: str = "") -> str | None:
    """Match hooks/_resolve-cli.sh and reject a mismatched CLI build identity."""
    import shutil
    import subprocess
    from pathlib import Path

    local = _cli_url_is_local(url)

    def identity_matches(candidate: Path, *, explicit: bool = False) -> bool:
        try:
            result = subprocess.run(
                [str(candidate), "status"],
                capture_output=True,
                text=True,
                check=False,
                timeout=2.0,
            )
        except (OSError, subprocess.SubprocessError):
            return explicit
        identity = next(
            (
                line.split(":", 1)[1].strip()
                for line in result.stdout.splitlines()
                if line.startswith("control_plane_url:")
            ),
            "",
        )
        if not identity:
            return explicit
        return _cli_url_is_local(identity) == local

    override = os.environ.get("SYNAPTORY_CLI_BIN")
    if override and os.path.isfile(override) and os.access(override, os.X_OK):
        path = Path(override)
        return str(path) if identity_matches(path, explicit=True) else None

    name = "synaptory-local" if local else "synaptory"
    candidates: list[Path] = []
    discovered = shutil.which(name)
    if discovered:
        candidates.append(Path(discovered))
    if local:
        prod = shutil.which("synaptory")
        if prod:
            candidates.append(Path(prod).parent / name)
    candidates.extend((Path.home() / ".local" / "bin" / name, Path.home() / "bin" / name))
    seen: set[str] = set()
    for candidate in candidates:
        rendered = str(candidate)
        if rendered in seen or not candidate.is_file() or not os.access(candidate, os.X_OK):
            continue
        seen.add(rendered)
        if identity_matches(candidate):
            return rendered
    return None


class ControlPlaneBackend(Backend):
    """Talks to the v2.5 control-plane via the `synaptory` Go CLI.

    v2.1.18+: when hooks/lib/cp-url(.local) is set + reachable AND the
    matching CLI (`synaptory` or `synaptory-local`) is on PATH, this backend
    invokes:

        synaptory login --if-needed --project <project> --json
        synaptory skills get <name>

    If the binary is missing or the CLI fails, the dispatcher falls back to
    LocalBackend so users are never blocked by a partial control-plane
    rollout. On v2.5 merge, LocalBackend is deleted; this backend stays.

    The CLI is expected to write a SessionRecord JSON to stdout on success,
    matching session_store.SessionRecord exactly. This is how the v2.5 Go
    CLI's keychain.Record structure gets bridged into the plugin.
    """

    def __init__(self, control_plane_url: str, cli_path: str | None = None):
        self.url = control_plane_url
        self.cli_path = cli_path or _resolve_cli_binary(control_plane_url)

    def name(self) -> str:
        return f"control-plane ({self.url})"

    def _run_cli(self, args: list[str], timeout: float = 30.0) -> tuple[int, str, str]:
        if not self.cli_path:
            raise SessionError(
                "synaptory CLI binary not found on PATH. Install the CLI that "
                "matches this plugin: `synaptory` for prod, `synaptory-local` "
                "after `./synaptory deploy local`."
            )
        import subprocess

        try:
            result = subprocess.run(
                [self.cli_path, *args],
                capture_output=True,
                text=True,
                timeout=timeout,
                env=dict(os.environ),
            )
            return result.returncode, result.stdout, result.stderr
        except subprocess.TimeoutExpired:
            raise SessionError(
                f"synaptory CLI timed out after {timeout}s "
                f"(URL: {self.url}). Network may be degraded; falling back "
                f"to local mode is safe for read-only skill access."
            )
        except OSError as e:
            raise SessionError(f"synaptory CLI exec failed: {e}")

    def login(self, project_id: str) -> SessionRecord:
        code, out, err = self._run_cli(
            ["login", "--if-needed", "--project", project_id, "--json"]
        )
        if code != 0:
            raise SessionError(
                f"synaptory login failed (exit {code}): {err.strip() or out.strip()}"
            )
        try:
            data = json.loads(out)
        except json.JSONDecodeError as e:
            raise SessionError(f"synaptory login returned non-JSON output: {e}")
        # CLI emits a SessionRecord-shaped JSON object identical to v2.5.
        try:
            record = SessionRecord.from_json(json.dumps(data))
        except (KeyError, ValueError) as e:
            raise SessionError(
                f"synaptory login JSON is missing fields (v2.5 shape expected): {e}"
            )
        # Persist locally so whoami works even if the CLI doesn't write its
        # own mirror file. Harmless on v2.5 where the Go CLI also writes.
        session_store.save(record)
        return record

    def fetch_skill_body(self, skill_name: str) -> str:
        code, out, err = self._run_cli(["skills", "get", skill_name])
        if code != 0:
            raise SessionError(
                f"synaptory skills get {skill_name} failed (exit {code}): "
                f"{err.strip() or 'no stderr'}"
            )
        return out


# ── Dispatcher ───────────────────────────────────────────────────────────────

def _discover_access_token() -> str | None:
    env = os.environ.get("SYNAPTORY_ACCESS_TOKEN")
    if env:
        return env.strip()
    home = os.path.expanduser("~/.synaptory-access-token")
    if os.path.exists(home):
        try:
            with open(home) as f:
                return f.read().strip()
        except OSError:
            return None
    proj_dir = _host_env().project_dir(".")
    proj = os.path.join(proj_dir, ".synaptory-access-token")
    if os.path.exists(proj):
        try:
            with open(proj) as f:
                return f.read().strip()
        except OSError:
            return None
    return None


def _control_plane_url() -> str:
    """Read the plugin-stamped URL. Env overrides are ignored."""
    return _host_env().plugin_control_plane_url()


def _control_plane_reachable(url: str, timeout: float = 2.0) -> bool:
    """Cheap liveness probe. Follows the user directive: URL set but
    unreachable → fall back to local, don't hard-fail.

    `SYNAPTORY_OFFLINE=1` short-circuits the probe and treats the CP as
    unreachable; matches the v2.5 Go CLI's offline flag.
    """
    if not url:
        return False
    if os.environ.get("SYNAPTORY_OFFLINE") == "1":
        return False
    try:
        import urllib.request

        req = urllib.request.Request(
            url.rstrip("/") + "/healthz",
            headers={"User-Agent": "synaptory-plugin"},
        )
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return 200 <= resp.status < 500
    except Exception:
        return False


class SessionManager:
    """Single entry point for the hook scripts."""

    def __init__(
        self,
        access_token: str | None = None,
        control_plane_url: str | None = None,
    ):
        self._access_token = access_token if access_token is not None else _discover_access_token()
        self._cp_url = (
            control_plane_url
            if control_plane_url is not None
            else _control_plane_url()
        )
        self._backend: Backend | None = None
        self._backend_name = "uninitialized"

    def _select_backend(self) -> Backend:
        if self._backend is not None:
            return self._backend

        if self._cp_url and _control_plane_reachable(self._cp_url):
            self._backend = ControlPlaneBackend(self._cp_url)
            self._backend_name = self._backend.name()
            return self._backend

        if not self._access_token:
            raise SessionError(
                "No access token found. Save your personal token:\n"
                '    echo "SYNAPTORY1..." > ~/.synaptory-access-token\n'
                "    chmod 600 ~/.synaptory-access-token"
            )

        self._backend = LocalBackend(self._access_token)
        self._backend_name = self._backend.name()
        return self._backend

    def _fallback_to_local(self, reason: str) -> Backend:
        if not self._access_token:
            raise SessionError(
                f"{reason} and no local access token available. "
                'Save your personal token: echo "SYNAPTORY1..." > ~/.synaptory-access-token'
            )
        self._backend = LocalBackend(self._access_token)
        self._backend_name = self._backend.name() + " (CP fallback)"
        return self._backend

    # ── Public interface ────────────────────────────────────────────────

    def login(self, project: str = DEFAULT_PROJECT) -> SessionRecord:
        backend = self._select_backend()
        try:
            return backend.login(project)
        except SessionError as e:
            if isinstance(backend, ControlPlaneBackend):
                return self._fallback_to_local(f"control-plane login failed: {e}").login(project)
            raise

    def whoami(self, project: str = DEFAULT_PROJECT) -> SessionRecord | None:
        url = self._cp_url or LOCAL_URL
        return session_store.load(url, project)

    def logout(self, project: str = DEFAULT_PROJECT) -> bool:
        url = self._cp_url or LOCAL_URL
        return session_store.delete(url, project)

    def activate(self, plugin_root: str, project: str = DEFAULT_PROJECT) -> dict:
        """Full SessionStart flow: login + decrypt the tree + write the
        /tmp/.synaptory-session-root marker. Returns a status dict.

        On success `login()` has written a SessionRecord to the store —
        `whoami()` will return it. On failure the store is left untouched.
        """
        record = self.login(project)

        if self._backend_name.startswith("control-plane") and not self._backend_name.endswith("(CP fallback)"):
            # Server-delivered skills — no local decryption needed.
            # v2.5 control-plane path. Return a minimal activation report.
            return {
                "status": "ok",
                "mode": "control-plane",
                "upn": record.upn,
                "expiry": record.expires_at.isoformat(),
                "role": record.role,
                "backend": self._backend_name,
                "stamped_count": 0,
                "copied_count": 0,
            }

        # Local mode — decrypt tree. The record has already been persisted by
        # login() above; we keep going even if decryption partially fails so
        # `whoami` stays useful for the next doctor call.
        if not self._access_token:
            raise SessionError("LocalBackend active but no access token present")
        try:
            result = atc.decrypt_all(
                self._access_token, plugin_root, atc.create_session_dir()
            )
        except (ValueError, RuntimeError) as e:
            raise SessionError(f"Skill decryption failed: {e}")

        result["mode"] = "local"
        result["backend"] = self._backend_name
        result["expiry"] = record.expires_at.isoformat()
        result["role"] = record.role
        return result

    def fetch_skill(self, name: str) -> str:
        backend = self._select_backend()
        try:
            return backend.fetch_skill_body(name)
        except SessionError as e:
            if isinstance(backend, ControlPlaneBackend):
                return self._fallback_to_local(
                    f"control-plane fetch_skill failed: {e}"
                ).fetch_skill_body(name)
            raise


# ── CLI ──────────────────────────────────────────────────────────────────────

def _parse_project(args: list[str]) -> str:
    if "--project" in args:
        i = args.index("--project")
        return args[i + 1] if i + 1 < len(args) else DEFAULT_PROJECT
    return DEFAULT_PROJECT


def _cli_login(args: list[str]) -> None:
    mgr = SessionManager()
    try:
        record = mgr.login(_parse_project(args))
    except SessionError as e:
        print(json.dumps({"status": "error", "error": str(e)}))
        sys.exit(1)
    print(json.dumps({
        "status": "ok",
        "upn": record.upn,
        "project_id": record.project_id,
        "role": record.role,
        "expires_at": record.expires_at.isoformat(),
        "backend": mgr._backend_name,
    }))


def _cli_whoami(args: list[str]) -> None:
    mgr = SessionManager()
    record = mgr.whoami(_parse_project(args))
    if record is None:
        print(json.dumps({"status": "no-session"}))
        sys.exit(1)
    print(json.dumps({
        "status": "ok",
        "upn": record.upn,
        "project_id": record.project_id,
        "role": record.role,
        "control_plane_url": record.control_plane_url,
        "expires_at": record.expires_at.isoformat(),
    }))


def _cli_logout(args: list[str]) -> None:
    mgr = SessionManager()
    ok = mgr.logout(_parse_project(args))
    print(json.dumps({"status": "ok" if ok else "no-session"}))


def _cli_activate(args: list[str]) -> None:
    if not args:
        print("Usage: session_manager.py activate <plugin_root> [--project <slug>]", file=sys.stderr)
        sys.exit(1)
    plugin_root = args[0]
    project = _parse_project(args[1:])
    mgr = SessionManager()
    try:
        result = mgr.activate(plugin_root, project)
    except SessionError as e:
        print(json.dumps({"status": "error", "error": str(e)}))
        sys.exit(1)
    print(json.dumps(result, indent=2))


def _cli_fetch_skill(args: list[str]) -> None:
    if not args:
        print("Usage: session_manager.py fetch-skill <name>", file=sys.stderr)
        sys.exit(1)
    mgr = SessionManager()
    try:
        print(mgr.fetch_skill(args[0]), end="")
    except SessionError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    if len(sys.argv) < 2:
        print(
            "Usage: session_manager.py <login|whoami|logout|activate|fetch-skill> [args...]",
            file=sys.stderr,
        )
        sys.exit(1)
    action = sys.argv[1]
    args = sys.argv[2:]
    actions = {
        "login": _cli_login,
        "whoami": _cli_whoami,
        "logout": _cli_logout,
        "activate": _cli_activate,
        "fetch-skill": _cli_fetch_skill,
    }
    if action not in actions:
        print(f"Unknown action: {action}", file=sys.stderr)
        sys.exit(1)
    actions[action](args)


if __name__ == "__main__":
    main()
