# GENERATED by plugin-cursor/scripts/compose.sh — edit core/ or plugin-claude/ then re-compose
"""Pluggable artifact adapter for synaptory ticket tracking.

Usage:
    from tracker import get_adapter
    adapter = get_adapter(project_dir)
    stories = adapter.list_stories(sprint=1)
"""

from pathlib import Path
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from .base import ArtifactAdapter
    from .config import SpecConfig

from .base import AdapterError, AdapterAuthError, AdapterOfflineError

# Cache key includes spec id when multi-spec — same project_dir / different spec
# id must yield different adapter instances (different cache paths / filter).
_adapter_cache: dict[str, "ArtifactAdapter"] = {}


def get_adapter(project_dir: Path, spec: Optional["SpecConfig"] = None) -> "ArtifactAdapter":
    """Get the configured adapter for a project directory.

    Returns a cached singleton per (project_dir, spec_id). The adapter type
    is determined by .synaptory.yaml (tracker.backend key). Multi-spec is
    supported by every backend. Remote backends scope by their native
    discriminator; the local backend scopes by filesystem path under
    `.synaptory/.orchestrator/specs/<id>/`.
    """
    spec_id = spec.id if spec is not None else ""
    key = f"{project_dir.resolve()}::{spec_id}"
    if key in _adapter_cache:
        return _adapter_cache[key]

    from .config import TrackerConfig
    config = TrackerConfig.load(project_dir)

    if config.backend == "github":
        from .github_adapter import GitHubAdapter
        adapter = GitHubAdapter(project_dir, config, spec=spec)
    elif config.backend == "jira":
        from .jira_adapter import JiraAdapter
        adapter = JiraAdapter(project_dir, config, spec=spec)
    elif config.backend == "teamwork":
        from .teamwork_adapter import TeamworkAdapter
        adapter = TeamworkAdapter(project_dir, config, spec=spec)
    elif config.backend == "linear":
        from .linear_adapter import LinearAdapter
        adapter = LinearAdapter(project_dir, config, spec=spec)
    elif config.backend == "local":
        # "local" is the default — compact JSON state plus Markdown artifacts.
        from .local_adapter import LocalAdapter
        adapter = LocalAdapter(project_dir, config, spec=spec)
    else:
        raise AdapterError(
            f"Unsupported tracker backend: {config.backend!r}. "
            "Supported backends: local, github, jira, teamwork, linear."
        )

    _adapter_cache[key] = adapter
    return adapter


def get_adapter_by_name(project_dir: Path, backend: str,
                        spec: Optional["SpecConfig"] = None) -> "ArtifactAdapter":
    """Instantiate a specific adapter by backend name, ignoring config.backend."""
    from .config import TrackerConfig
    config = TrackerConfig.load(project_dir)
    config.backend = backend

    if backend == "github":
        from .github_adapter import GitHubAdapter
        return GitHubAdapter(project_dir, config, spec=spec)
    elif backend == "jira":
        from .jira_adapter import JiraAdapter
        return JiraAdapter(project_dir, config, spec=spec)
    elif backend == "teamwork":
        from .teamwork_adapter import TeamworkAdapter
        return TeamworkAdapter(project_dir, config, spec=spec)
    elif backend == "linear":
        from .linear_adapter import LinearAdapter
        return LinearAdapter(project_dir, config, spec=spec)
    elif backend == "local":
        from .local_adapter import LocalAdapter
        return LocalAdapter(project_dir, config, spec=spec)
    raise AdapterError(
        f"Unsupported tracker backend: {backend!r}. "
        "Supported backends: local, github, jira, teamwork, linear."
    )


def resolve_spec(project_dir: Path, spec_flag: Optional[str] = None) -> Optional["SpecConfig"]:
    """Resolve the active SpecConfig for a CLI invocation.

    Resolution order (design §6.1):
      1. Explicit `--spec=<id>` flag.
      2. `pipeline-state.json.active_spec` (the persisted default).
      3. None — legacy single-spec mode.

    Errors:
      - Raises ValueError when multi-spec is configured but neither the
        flag nor `active_spec` resolves to a known spec.
      - Raises ValueError when an explicit flag points at an unknown spec id.
    """
    from .config import TrackerConfig
    config = TrackerConfig.load(project_dir)
    if not config.is_multispec():
        if spec_flag:
            raise ValueError(
                f"--spec={spec_flag!r} given but no `specs:` block in "
                ".synaptory.yaml — this is a single-spec project."
            )
        return None

    if spec_flag:
        sc = config.find_spec(spec_flag)
        if sc is None:
            raise ValueError(
                f"--spec={spec_flag!r}: unknown spec id. "
                f"Known: {[s.id for s in config.specs]}"
            )
        return sc

    # Fall back to active_spec from pipeline-state.json
    active = _read_active_spec(project_dir)
    if active:
        sc = config.find_spec(active)
        if sc is not None:
            return sc

    raise ValueError(
        "Multi-spec project but no active spec — pass --spec=<id> or set "
        f"pipeline-state.json.active_spec. Known specs: {[s.id for s in config.specs]}"
    )


def _read_active_spec(project_dir: Path) -> Optional[str]:
    import json as _json
    p = project_dir / ".synaptory" / ".orchestrator" / "pipeline-state.json"
    if not p.exists():
        return None
    try:
        state = _json.loads(p.read_text(encoding="utf-8"))
    except (OSError, _json.JSONDecodeError):
        return None
    active = state.get("active_spec")
    return active if isinstance(active, str) and active else None


def clear_cache() -> None:
    """Clear the adapter cache (useful for testing)."""
    _adapter_cache.clear()
